### ISSUE TITLE
Multiple Checksum in same packet

### ISSUE THREAD

**Issue by TsahiM** [jefffhaynes/BinarySerializer#103]
Hi,
I started looking into this project and I think this library is what I was looking for

I am facing an issue that the packets I need to send to the devices include two checksums, one for the header object and 2nd for the entire message but without the 1st checksum value

I tried with library's checksum and my own checksum attribute, and could not figure out how to do it

Any idea?

Thank you!

**Comment by jefffhaynes** [comment]
Can you give me an idea (maybe a diagram?) of the header/body layout with crcs?  Thanks

—
If you want to build a ship, don't drum up people to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.

Antoine de Saint-Exupery
________________________________

**Comment by TsahiM** [comment]
The structure of the messages is something like this

- start characters
- Code
- Data Length
- Header Checksum which is the sum of start  + code + length
- Data
- Checksum which is the sum of start  + code + length + Data

I am trying to avoid that the value of the header checksum will be included in the 2nd checksum
I tried implementing my own checksum (deriving from FieldValueAttributeBase) but I could not find a way to skip header checksum in GetUpdatedState


Thank you!

**Comment by jefffhaynes** [comment]
Yeah, what a weird format. That’s tricky, let me think about it. Maybe there should be a way to ignore fields in value computations.

—
If you want to build a ship, don't drum up people to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.

Antoine de Saint-Exupery
________________________________

**Comment by jefffhaynes** [comment]
I’m going to see if there’s a way to make multiple CRC declarations aggregate on a single field. I’m not sure if it will work given the design but I think it could make sense if it does.

**Comment by VDBorovikov** [comment]
Hi Jeff.
It would be great. So we don't need any wrappers to calculate crc on
multiple fields. Except of such wired things))


вс, 1 апр. 2018 г., 19:17 Jeff Haynes <notifications@github.com>:

**Comment by jefffhaynes** [comment]
I think this is doable but a little tricky. It will probably take some time to get right.

**Comment by jefffhaynes** [comment]
Pushed in 8.1

**Comment by TsahiM** [comment]
Hi Jeff, Thank you so much

I am still struggling to make it to work
I created my own checksum attribute, deriving from FieldValueAttributeBase, since it is a bit different
And came up with this data structure :

    [FieldOrder(0)]
    [ChecksumAtt(nameof(Checksum1))]
    public byte header { get; set; }

    [FieldOrder(1)]
    [ChecksumAtt(nameof(Checksum1))]
    public short Code { get; set; }

    [FieldOrder(2)]
    [ChecksumAtt(nameof(Checksum1))]
    public short dataLength { get; set; }

    [FieldOrder(3)]
    [ChecksumAtt(nameof(Checksum2))]
    public short Checksum1 { get; set; }

    [FieldOrder(4)]
    [Subtype(nameof(Code), 1, typeof(Type1))]
    [Subtype(nameof(Code), 2, typeof(Type2))]
    [Subtype(nameof(Code), 3, typeof(Type3))]
    [Subtype(nameof(Code), 4, typeof(Type4))]
    [FieldLength(nameof(dataLength))]
    [ChecksumAtt(nameof(Checksum2))]
    public BaseType FrameContent { get; set; }

    [FieldOrder(5)]
    public UInt16 Checksum2 { get; set; }

No Issue with the Checksum1 but serialization of Checksum2 doesn’t produce the correct value
I see GetInitialState is called 4 times 
At some point, it even has the correct value but then it gets initialized (GetInitialState) again and again
After the last time that GetInitialState is getting called, the buffer I get in GetUpdatedState include only FrameConent, without Checksum1

Any idea?

**Comment by jefffhaynes** [comment]
I would expect it to be called multiple times because it’s measuring the content length. Can you post your checksum code so I can try it out?

________________________________

**Comment by TsahiM** [comment]
Hi,
I am looking in providing my own length instead of the built-in, for now, it looks good

Thanks

**Comment by demon-iak** [comment]
The built in CRC32Attribute also has the same issue.

**Comment by jefffhaynes** [comment]
Yeah, it's a side-effect of the length measure.  Essentially the framework doesn't know that you're not going to need the CRC for the length measure so it calculates it during the measure phase.  Is your issue that it's causing performance problems?  I could potentially add a check for that but it would introduce some complexity into the design.

**Comment by demon-iak** [comment]
@jefffhaynes The CRC of the "FieldLength" binding field has been calculated an extra time, so the total CRC is **wrong**.

**Comment by jefffhaynes** [comment]
Oh! Sorry, I didn’t understand what you were saying.  I tried to reproduce but I didn’t have the length binding. I’ll work on it today.

________________________________

**Comment by jefffhaynes** [comment]
What is the expected behavior of your class definition?  You're binding two fields to a single CRC field.  That should actually error, which I think is the real bug here.  Those two fields aren't going to result in the same CRC so this isn't really a valid definition.

**Comment by jefffhaynes** [comment]
Disregard, I forgot I changed the behavior of the value field to aggregate...

**Comment by jefffhaynes** [comment]
Confirmed this is a bug.  A devious one too...

**Comment by jefffhaynes** [comment]
Sorry about that, it took me a while to get my head around what was happening.  Try 8.1.3 and let me know if you have any issues.

**Comment by demon-iak** [comment]
Great work, man. I tested it and it is OK now.

**Comment by jefffhaynes** [comment]
Awesome, glad to hear it.

________________________________
