### ISSUE TITLE
Endianess of bit fields

### ISSUE THREAD

**Issue by mixandmatch025** [jefffhaynes/BinarySerializer#106]
I've been playing around with bit fields and it appears that FieldEndianessAttribute has no effect on fields with FieldBitLengthAttribute. Is there something I'm missing?
Is there any way to change the endianess of bit fields?

**Comment by jefffhaynes** [comment]
That’s correct. Endianness is defined at a byte level so I don’t know that it would make sense. Can you give an example of what you’re looking to do?

________________________________

**Comment by mixandmatch025** [comment]
For example serializing the following class - 
```
public class Buffer
{
   [FieldOrder(0)]
   [FieldBitLength(2)]
   public byte Field1 {get;set;}

   [FieldOrder(1)]
   [FieldBitLength(7)]
   public byte Field2 {get;set;}

   [FieldOrder(2)]
   [FieldBitLength(7)]
   public byte Field3 {get;set;}

   [FieldOrder(3)]
   public byte Field4 {get;set;}
}
```
if Field1 = 0x01, Field2 = 0x10, Field3 = 0x40, Field4 = 0xFF
The result would be { 0x48, 0x40, 0xFF } or in bits - { 0b01001000, 0b01000000, 0b11111111 }.
I would want the result to be { 0x41, 0x80, 0xFF } - { 0b01000001, 0b10000000, 0b11111111 }.
Where the difference between the two, to my understanding, is the endianess of the bit fields.
Today this can be achieved by reversing the order of the values of the FieldOrders and reversing the resulting buffer.

**Comment by jefffhaynes** [comment]
I haven’t had a chance to draw this all out so I don’t fully understand the difference between your two examples but I don’t think it’s an issue of endianness. Endianness only applies to values that are greater than one byte in length, so typically shorts, ints, longs, etc wherein the ordering of the bytes (not bits) is reversed.

Anyway, I’ll try to sketch it out this weekend and see if I can come up with a better answer.

________________________________

**Comment by jefffhaynes** [comment]
Ah, I understand. I think this is referred to as bit numbering (or bit-endianness). Ok, it probably makes sense to support that albeit likely with a different mechanism than the endianness attribute. I can work on that.

________________________________

**Comment by mixandmatch025** [comment]
Thanks, much appreciated.
Let me know if there is anything I can help with. I am not that familiar with this repo, but if pointed in the right direction I'll be glad to help.

**Comment by jefffhaynes** [comment]
Thanks, I will. It’s actually a tricky update so I need to think more about the best approach.

________________________________

**Comment by jefffhaynes** [comment]
Sorry, I just came across this now but it was fixed in an update some time ago.
