### ISSUE TITLE
Add a license file to repository

### ISSUE THREAD

**Issue by Genteure** [jefffhaynes/BinarySerializer#108]
You don't have a license file in this repository nor mentioned license choice in README, although I do notice you had set a license on the nuget page.

[Licensing a repository](https://help.github.com/articles/licensing-a-repository/)

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by jefffhaynes** [comment]
Good point, thanks

________________________________
