### ISSUE TITLE
How get the FieldLength with Binding

### ISSUE THREAD

**Issue by A016699** [jefffhaynes/BinarySerializer#115]
I'm using your in some project and I'm very happy with it. It works well and has a great performance. Now I have a Project where I want to use own serialization class using the IBinarySerializable. I also want to use the FieldLengthAttribute with Binding like show here in the example:

```
public class Packet
    {
        [FieldOrder(10)]
        public int Size { get; set; }

        [FieldOrder(20)]
        [FieldLength("Size")]
        public PacketPayLoad PayLoad { get; set; }
    }
public class PacketPayLoad : IBinarySerializable
    {
        public void Deserialize(Stream stream, Endianness endianness, BinarySerializationContext serializationContext)
        {
            // How get the FieldLength ?
        }

        public void Serialize(Stream stream, Endianness endianness, BinarySerializationContext serializationContext)
        {
           
        }
    }
```
I get the Attribute - but how I get the Value of the binded field ?

**Comment by jefffhaynes** [comment]
During deserialization the stream that is passed to you should be limited to the length of the field.  However, I don’t think you can query the length of the stream as that assumes an underlying seekable stream.


________________________________

**Comment by jefffhaynes** [comment]
If that’s a problem let me know and I can look at trying to make it queryable in situations like this.


________________________________

**Comment by A016699** [comment]
Thank you for that that is fine then for me.

**Comment by jefffhaynes** [comment]
Cool, glad to hear it.

________________________________
