### ISSUE TITLE
Chicken and Egg when working with EA-IFF 85

### ISSUE THREAD

**Issue by jda808** [jefffhaynes/BinarySerializer#12]
Having a hard time finalizing my implementation for some knarly EA-IFF 85 form chunks.
No matter how I strucuture or wire it up, I always end up having to implement IbinarySerializer. The stream position refuses to increase when I try to add padding via converts or props.
![chunkhierarchy](https://cloud.githubusercontent.com/assets/860690/7236837/12d59ce6-e75d-11e4-90d1-d7bb5f28d975.png)

there are 0 or more REFE chunks and the AUTH chunk is optional.

here's one (of about 10) different ways I've tried implementing REFS:

'''
	/// <summary>
	/// There is a REFE chunk for every reference to XXX
	/// you can have 0 or more REFE chunks. Currently we work with 
	///  two versions of this chunk: the version wriXXXXXXXXX
	/// </summary>
	public class RefeChunk //: IffChunk //, IBinarySerializable
	{

		[FieldOrder(0)]
		[FieldLength(4)]
		public string ChunkName { get; set; }

		[FieldOrder(1)]
		[SerializeAs(Endianness = Endianness.Big)]
		public UInt32 ChunkSize { get; set; }

		[FieldOrder(2)]
		[FieldLength("ChunkSize")]
		[SerializeAs(Encoding = "UTF-8", Endianness = Endianness.Big)] //, SerializedType = SerializedType.ByteArray)]																												
		public RefePayload RefePayload { get; set; }

		//public byte[] RefePayload { get; set; }

		[Ignore]
		public int PadLength
		{
			get { return (ChunkSize % 2 == 0) ? 0 : 1; }
		}

		[FieldOrder(3)]
		//[SerializeAs(SerializedType = SerializedType.ByteArray)]
		//[FieldLength("PadLength")]	//, ConverterType = typeof(PadHackConverter)]
		//[SerializeAs(SerializedType = SerializedType.ByteArray)]
		[SerializeWhen("PadLength", 1)]
		//[FieldLength("PadLength")]
		public byte Padding { get; set; } =0x00;

		//
		//public RefeChunk() : base("REFE")
		//{
		//}

		//public void Serialize(Stream stream, Endianness endianness, BinarySerializationContext serializationContext)
		//{
		//	throw new NotImplementedException();
		//}

		//public void Deserialize(Stream st, Endianness endianness, BinarySerializationContext serializationContext)
		//{
		//	BinarySerializer bs = new BinarySerializer();
		//	EndianAwareBinaryReader br = new EndianAwareBinaryReader(st, Endianness.Big);
		//	bs.Endianness = Endianness.Big;
		//	this.ChunkName = new string(br.ReadChars(4));
		//	this.ChunkSize = br.ReadUInt32();
		//	this.ChunkVersion = bs.Deserialize<WankyVersion>(st);
		//	Debug.IndentLevel = 0;
		//	Debug.WriteLine(this.ChunkName + " size:" + this.ChunkSize + " " + this.ChunkVersion);
		
		//	this.RPV3= bs.Deserialize<RPV3>(st);
		
		//	this.DBV3= bs.Deserialize<DBV4>(st);
		//	byte B13 = br.ReadByte();
		//	this.Reserved13 = B13;
		//	Debug.WriteLineIf(this.Reserved13 != 13, "!!!!!!!!!!! RESERVED BYTE 13 iS BAD !!!!!!!!!!!! (SLAPS WRIST)");
		//	if (this.ChunkVersion >= this.MaxVersion)
		//	{
		//		Debug.WriteLine("REFE Chunk version is >= 1,3,0 so we are going to parse some more stuff...");
		//		//OTHER STUFF blah blah
		//	}
		//	//if odd size, read an extra byte
		//	if (ChunkSize % 2 != 0)
		//	{
		//		byte stubbbby = br.ReadByte();
		//	}
		//	//db
		//	//a
		//}

Surely there is a way to avoid IBinarySerializer for such a simple concept, right?

**Comment by jefffhaynes** [comment]
Yes, I think so.  Let me work on it.

**Comment by jefffhaynes** [comment]
I think the correct way to implement this is with a recursive object structure.  However, currently the implementation doesn't support recursive objects.  Let me work on fixing that and then I'll post a solution, thanks.

**Comment by jefffhaynes** [comment]
Ok, try something like using the new 4.0 I just pushed.

    public abstract class Chunk
    {
    }

    public class FormChunk : Chunk
    {
        [FieldOrder(0)]
        [FieldLength(4)]
        public string TypeId { get; set; }

        [FieldOrder(1)]
        public List<ChunkContainer> Chunks { get; set; }
    }

    public class CatChunk : Chunk
    {
        public List<ChunkContainer> Chunks { get; set; } 
    }

    public class RefeChunk : Chunk
    {
        [SerializeAs(SerializedType.SizedString)]
        public string SomeStuffInThisChunk { get; set; }
    }

    public class ChunkContainer
    {
        [FieldOrder(0)]
        [FieldLength(4)]
        public string TypeId { get; set; }

        [FieldOrder(1)]
        [SerializeAs(Endianness = BinarySerialization.Endianness.Big)]
        public int ChunkLength { get; set; }

        [FieldOrder(2)]
        [FieldLength("ChunkLength")]
        [Subtype("TypeId", "FORM", typeof(FormChunk))]
        [Subtype("TypeId", "CAT ", typeof(CatChunk))]
        [Subtype("TypeId", "REFE", typeof(RefeChunk))]
        public Chunk Chunk { get; set; }

        [FieldOrder(3)]
        [SerializeWhen("ChunkLength", false, ConverterType = typeof(IsEvenConverter))]
        public byte Pad { get; set; }
    }

    public class IsEvenConverter : IValueConverter
    {
        public object Convert(object value, object parameter, BinarySerializationContext context)
        {
            var intValue = System.Convert.ToInt32(value);
            return intValue%2 == 0;
        }

        public object ConvertBack(object value, object parameter, BinarySerializationContext context)
        {
            throw new NotImplementedException();
        }
    }

And so on...let me know if it works or not, thanks.

**Comment by jda808** [comment]
This is great! Feels like you read my mind. I

**Comment by jefffhaynes** [comment]
Awesome, glad to hear it. Not sure if your comment got truncated but did you get it to work?

**Comment by jda808** [comment]
Chevking now. And yes, I had a PEBKAC issue with the web browser.

**Comment by jda808** [comment]
it looks like you fixed some initialization issues. It appears I no longer have to explicitly initialize complex objects. The recursive support is much appreciated.

Tried adjusting the example but can't get it to work. There's an additional chunk that sits between CAT and REFE, called REFS (see below). REFS has 0 or more REFE's. Either padding gets off for DESC or there's padding issues between the REFEs, or the last REFE is not complete. I've tried tackling this with ItemSerializeUntil, SerializeWhen, and FieldLength... but can't seem to get it ironed out.

Parameter | UNIT | Description
-------------|---------|--------
Form | char(4) | "FORM"
length|UInt32| size
ChunkName|char(4)|"PTCH"

The REFS chunk contains ZERO or more REFE chunks:

Parameter | UNIT | Description
-------------|---------|--------
Cat | char(4) | "CAT "
length|UInt32|Size
ChunkName|char(4)|"REFS"

There's the REFE chunks: 0 or more...

Parameter | UNIT | Description
-------------|---------|--------
ChunkName | char(4) | "REFE"
length|UInt32|Size
...|....|...

Then a DESC chunk. It's always there 
Parameter | UNIT | Description
-------------|---------|--------
ChunkName | char(4) | "DESC"
length|UInt32|Size
stuff|stuff|stuff

The BEER chunk is optional. Sometimes its there sometimes it not.
Parameter | UNIT | Description
-------------|---------|--------
ChunkName | char(4) | "AUTH"
length|UInt32|Size
...|....|...

There are whole bunch of other chunks but we need one more to complete the use case let's call it
"SNAX"
Parameter | UNIT | Description
-------------|---------|--------
ChunkName | char(4) | "SNAX"
length|UInt32|Size
...|....|...

**Comment by jefffhaynes** [comment]
I updated the example code at https://github.com/jefffhaynes/BinarySerializer/tree/master/BinarySerializer.Test/Issues/Issue12

It looks like I probably left a chunk name field out of the CAT chunk.  However, just to be clear (assuming I'm reading the IFF spec correctly), there are Type IDs, and there are names (sometimes confusingly called types).  Not all chunk types appear to have names, but all chunk types must have Type IDs (e.g. FORM, LIST, CAT , etc.).  I'm assuming "REFS" is the *name* for a chunk with Type ID "CAT ".  So when you list, for example, "SNAX" as the chunk name, I don't think that's correct.  SNAX would be the Type ID, not the name.

Essentially, it seems to me that every chunk starts with TypeID and Length (these fields show up in the ChunkContainer class in my code).  Then within a specific chunk (only FORM and CAT as far as I can tell) there may be a Name field specified.  Again, that doesn't appear to be true for all chunk types.

As for padding, I believe the Pad field in the ChunkContainer class will always correctly adjust for odd padding irrespective of the chunk definition as it is bound to the local chunk length via a converter.

The real "magic" in the code comes from the Subtype attributes, which tell the serializer which chunk type to serialize or deserialize based on the TypeID field.  If you need to add additional chunk types, just declare them and add a corresponding Subtype attribute in the ChunkContainer class.

Do you have example files you're using to test this?  If so, it would be nice if I could commit one into the unit test for this.

**Comment by jda808** [comment]
Gladly send you some example data. Do you want my existing unit test as
well? Should I push it through git or can i just email you a zip file?

**Comment by jefffhaynes** [comment]
You can email it if you want.

feedyurhed at gmail

**Comment by jda808** [comment]
The padding works brilliantly, it looks like some LazyLoad issues going on... 

			//This Doesn't work. Deep in the graph objects are not set to reference
			FormChunk form = bs.Deserialize<FormChunk>(st);

			//This works to a point, but fails at the body chunk
			br.ReadChars(4);
			br.ReadUInt32();
			br.ReadChars(4);
			br.ReadChars(4);
			br.ReadUInt32();
			br.ReadChars(4);
			var refs = bs.Deserialize<ChunkContainer>(st);
			var desc = bs.Deserialize<ChunkContainer>(st);
			var parm = bs.Deserialize<ChunkContainer>(st);
			var body = bs.Deserialize<ChunkContainer>(st); //<-- Body chunk has nested class that has a List with a SerializeWhen Attribute that uses a converter. 

			//This Does work though
			br.ReadChars(4);
			br.ReadUInt32();
			br.ReadChars(4);
			br.ReadChars(4);
			br.ReadUInt32();
			br.ReadChars(4);
			var refs = bs.Deserialize<ChunkContainer>(st);
			var desc = bs.Deserialize<ChunkContainer>(st);
			var parm = bs.Deserialize<ChunkContainer>(st);
			br.ReadChars(4);
			br.ReadUInt32();
			var bodyChunk = bs.Deserialize<BodyChunk>(st);

**Comment by jefffhaynes** [comment]
Yeah, I'm looking at it now.  You actually need to Deserialize<ChunkContainer>, not <FormChunk> at the top.  However, there is still something going on further down...

**Comment by jefffhaynes** [comment]
I just got it working.  I think there were just missing chunks (BODY and PARM).  The details of the chunks are missing but 1Z1S deserializes.  Take a look...

**Comment by jefffhaynes** [comment]
Did you get this to work?

**Comment by jda808** [comment]
Are the builds between Nuget & your Github repositiory the same? If I update my clone using fetch via git then the assembly version shows 4.0.1. The version on Nuget repo says 4.0.2. 

If they are, then no, not yet. Got the afternoon allocated to dig in deeper. 

FWIW
Saw 4.0.2 update via nuget. I wasn't paying attention to what I was doing and updated the Nuget Extension for VS 2015. Now when I go to update the package, the install fails. Apparently the nuget extension update is not compatible with CTP6. It appears I have to reinstall vs 2015 to restore nuget functionality (rest of the machines minus build Win32 server are Macs!)  

.

**Comment by jefffhaynes** [comment]
No, I noticed this morning that I failed to commit 4.0.2 to github. I'll fix it tonight.

**Comment by jda808** [comment]
Just tried out 4.0.2. No luck. Additionally, the workarounds I was using to force initialization on earlier builds no longer work.

**Comment by jefffhaynes** [comment]
github is updated now (to 4.0.3 to fix a bug with ignore fields) but I haven't had a chance to look at the files you sent me yet.

**Comment by jda808** [comment]
Now I'm getting different results on our Tests. Some are now failing.
Test Name:	xxxxStringReadWrite
Test Outcome:	Failed
Result Message:	
Test method .Tests.xxxxStringTests.xxxxStringReadWrite threw exception: 
System.InvalidOperationException: Error deserializing . ---> System.InvalidOperationException: Error deserializing . ---> System.ArgumentException: Version Header Mismatch should be 0xbc actual:0
Result StandardOutput:	
Debug Trace:
Encoding Utf-8 byte count:24 string length:12
Endi is:Little Encoding is:System.Text.UTF8Encoding
Identifier: 4294967295
ReservedHead: 0
Major: 1
Minor: 0
Revision: 0
PostReserved: 0

Test Name:	ReasonStringReadWrite
Test FullName:	Pandacorn.xxx.xxxx.Tests.xxxxxStringTests.xxxxStringReadWrite
Test Source:	C:\xxxxxxxx\xxxxxStringTests.cs : line 27
Test Outcome:	Failed
Test Duration:	0:00:00.0210782

Result StackTrace:	
at Pandacorn.Core.xxxx.xxxxVersion.set_ReservedHead(Byte value) in xxxxxxx\xxxx\WonkyVersion.cs:line 40
   at BinarySerialization.MagicMethods.<>c__DisplayClass3_0`2.<MagicActionHelper>b__0(Object target, Object value) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\MagicMethods.cs:line 70
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.get_Value() in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ObjectValueNode.cs:line 66
   at BinarySerialization.Graph.ValueGraph.ObjectValueNode.DeserializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ObjectValueNode.cs:line 173
   at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 157
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 175
   at BinarySerialization.Graph.ValueGraph.ContextValueNode.DeserializeOverride(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ContextValueNode.cs:line 91
   at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 157
 --- End of inner exception stack trace ---
    at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(StreamLimiter stream, EventShuttle eventShuttle) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs:line 175
   at BinarySerialization.BinarySerializer.Deserialize[T](Stream stream, Object context) in C:\s\3rd\social\github\BinarySerializer\BinarySerializer\BinarySerializer.cs:line 161
   at Pandacorn.Core.xxxxx.Tests.xxxxStringTests.xxxxStringReadWrite() in C:\s\pcrn\shrimpLotus\Pandacorn.Core.Tests\xxxx\xxxxStringTests.cs:line 49
Result Message:	
Test method Pandacorn.Core.xxxx.Tests.xxxxStringTests.xxxxStringReadWrite threw exception: 
System.InvalidOperationException: Error deserializing . ---> System.InvalidOperationException: Error deserializing . ---> System.ArgumentException: Version Header Mismatch should be 0xbc actual:0

**Comment by jefffhaynes** [comment]
Based on our conversations I think this is all set now but correct me if I'm wrong.
