### ISSUE TITLE
Enum Type with two constants using the same value throws an exception

### ISSUE THREAD

**Issue by cmeyla** [jefffhaynes/BinarySerializer#121]
I have an enum (an enum defined by Microsoft) that contains two constants that share the same value. This errors when deserializing with 'ArgumentException: An item with the same key has already been added.'  So it appears the enum values are being used as keys in some dictionary!

An example:

public enum TestValues
{
  Zero = 0,
  One = 1,
  Two = 1
}

**Comment by jefffhaynes** [comment]
That’s correct. Because there is a value collision, the serialized doesn’t know which enum to use during deserialization.  I take it you were expecting something else?


________________________________

**Comment by cmeyla** [comment]
Nah!

I didn't know what the problem was because the enum contains hundreds of
values and it took a while to figure it out!

That makes sense; not sure why MS uses multiple named constants for the
same value!  I encountered this during manual (custom) serialization and
hadn't thought about the declarative nature of the library in a while!
