### ISSUE TITLE
Support for FieldBitLength Binding

### ISSUE THREAD

**Issue by demon-iak** [jefffhaynes/BinarySerializer#124]
Can FieldBitLength binding like FieldLength?
 It will be useful when some length is presented by bit .

**Comment by jefffhaynes** [comment]
If the bit length is evenly divisible by 8 then I would just use a converter and a normal fieldlength.  Do you have a situation where a field length is expressed in an arbitrary number of bits?  And if so can you share it so I have an example to work with?  Thanks.

**Comment by demon-iak** [comment]
Hi @jefffhaynes, I'm currently using BinarySerializer for [ETCS (European Train Control System)](https://en.wikipedia.org/wiki/European_Train_Control_System)protocols that used for Train Control . The protocols count is very huge, and they all fellow a basic patten:

![capture](https://user-images.githubusercontent.com/3446094/52755272-59898f80-3038-11e9-9450-eb3a3b9d7821.PNG)
L_MESSAGE is the Application message total length in byte, from Message Header to Padding bits.
L_PACKET is the Packet total length in bit, including NID_PACKET.
Here is my code:
```C#
 
    public class ApplicationMessage
    {
        [FieldOrder(1)]
        [FieldBitLength(10)]
        public byte NID_STM { get; set; }


        [FieldOrder(2)]
        [FieldBitLength(13)]
        public ushort L_MESSAGE { get; set; }

        [FieldOrder(3)]
        // L_MESSAGE = (bit length of List<Packet> + bit length of NID_STM(10) + bit length of L_MESSAGE(13) + bit length  of PaddingBits ) /8
        [FieldLength(nameof(L_MESSAGE), ConverterType = typeof(L_MESSAGEConverter))]
        [ItemSerializeUntil(nameof(Packet.NID_PACKET), null)]
        public List<Packet> Packets;

        //PaddingBits bit length = L_MESSAGE * 8 - bit length of List<Packet> - bit length of NID_STM(10) - bit length of L_MESSAGE(13)
        [FieldOrder(4)]
        public byte PaddingBits { get; set; }
    }
    public class Packet
    {

        [FieldOrder(1)]
        [FieldBitLength(10)]
        public byte NID_PACKET { get; set; }

        [FieldOrder(2)]
        [FieldBitLength(13)]
        public ushort L_PACKET { get; set; }

        [FieldOrder(3)]
        [SerializeWhenNot(nameof(NID_PACKET), null)]
        [Subtype(nameof(NID_PACKET), NID_PACKETNUM.PACKET1, typeof(Packet1))]
        [Subtype(nameof(NID_PACKET), NID_PACKETNUM.PACKETN, typeof(PacketN))]
        //L_PACKET = bit length of PacketBody + bit length of NID_PACKET(10)+ bit length of L_PACKET(13)
        [FieldBitLength(nameof(L_PACKET), ConverterType = typeof(L_PACKETConverter))]
        public PacketBody PacketBody { get; set; }

    }

    public class PacketBody
    {
    }
    public class Packet1 : PacketBody
    {
        //Other variables
    }

    public class PacketN : PacketBody
    {
        //Other variables
    }

    public enum NID_PACKETNUM
    {
        PACKET1,
        PACKETN
    }
```

The problems are:
1.During serialization, the PaddingBits can not be calculated because BinarySerializer Thinks it is the NID_PACKET of next packet.
2. During deserialization, L_PACKET  can not be calculated because FieldBitLength can not use bindings and converter. And L_MESSAGE  can not be calculated because L_PACKET  can not be calculated.
Think you!

**Comment by jefffhaynes** [comment]
Ah, you’re using it to control trains...that’s terrifying.

Ok I’ll try to take a look this weekend :)


________________________________

**Comment by jefffhaynes** [comment]
Added in 8.2
