### ISSUE TITLE
I don't know what I missed.

### ISSUE THREAD

**Issue by 463728946** [jefffhaynes/BinarySerializer#131]
static void Main(string[] args)
        {
            var a = new byte[] { 0x01, 0x01 };
            var serializer = new BinarySerializer();
            var message = serializer.Deserialize<TestClass>(a);
            using (var ms = new MemoryStream())
            {
                serializer.Serialize(ms, message);
                var array = ms.ToArray();  //it's should be {1,1},but i don't why it's {4,1,0,0,0}
            }
        }

        public class TestClass
        {
            [FieldOrder(0)]
            [FieldLength(1)]
            public int DataLength { get; set; }

            [FieldOrder(1)]
            [FieldLength("DataLength")]
            //[FieldLength(1)]                  //it's work
            [SubtypeDefault(typeof(TestType))]
            public TestType Type { get; set; }
        }

        public enum TestType
        {
            A, B, C, D, E, F
        }

**Comment by jefffhaynes** [comment]
FieldLength attributes on primitive types are not supported (although it should probably throw an exception).

Try using:

`public byte DataLength`

**Comment by 463728946** [comment]
I tried it, but I couldn't.
anyway, I used [FieldLength(1)].because my 'DataLength' fixed length.
