### ISSUE TITLE
How to Bind Datetime and customer like Latitude Longitude

### ISSUE THREAD

**Issue by 463728946** [jefffhaynes/BinarySerializer#132]
var bytes = new byte[]{0x0D,0x74,0x51,0x78,0x43,0x8E,0x6E,0xC4};
//They should be:
//Latitude    [22.5726840]
//Longitude    [113.3407940]
//
//but they are:
//Latitude    -99.9387581
//Longitude   201.8604045

public class Coordinates
{
    [FieldOrder(0)]
    [FieldScale(10000000)]
    [SerializeAs(SerializedType.Int4)]
    public double Longitude { get; set; }
    [FieldOrder(1)]
    [FieldScale(10000000)]
    [SerializeAs(SerializedType.Int4)]
    public double Latitude { get; set; }
}

**Comment by jefffhaynes** [comment]
I don’t think the decimal type is supported. I would recommend using float instead.


________________________________

**Comment by 463728946** [comment]
sorry ,I don't get it

**Comment by jefffhaynes** [comment]
Looks like you're expecting big endian.  Try this:

```c#
public class Coordinates
{
    [FieldOrder(0)]
    [FieldScale(10000000)]
    [SerializeAs(SerializedType.Int4)]
    [FieldEndianness(Endianness.Big)] 
    public double Longitude { get; set; }

    [FieldOrder(1)]
    [FieldScale(10000000)]
    [SerializeAs(SerializedType.Int4)]
    [FieldEndianness(Endianness.Big)]
    public double Latitude { get; set; }
}
```

**Comment by 463728946** [comment]
amazing！It's great. thank u so much
