### ISSUE TITLE
Can I Deserialize Hex String？

### ISSUE THREAD

**Issue by 463728946** [jefffhaynes/BinarySerializer#133]
Hi Jeff!

        static void Main(string[] args)
        {            
            var bytes = new byte[] { 0x45, 0x62, 0x42, 0x92, 0x46 }; 
            var serializer = new BinarySerializer();
            var message = serializer.Deserialize<TextClass>(bytes);
            //how can i get "4562429246"??
        }

        public class TextClass
        {          
            [FieldOrder(0)]           
            [FieldLength(5)] 
            public string MobileID { get; set; }
        }

**Comment by jefffhaynes** [comment]
You would have to write a custom serializer for this. This is more of a “convert” function than a serialization function so the framework doesn’t support it.

Why not just add a second property or method that returns that value in hex?


________________________________

**Comment by 463728946** [comment]
Thank you for your reply
