### ISSUE TITLE
Support FieldScale for integer types

### ISSUE THREAD

**Issue by LordMike** [jefffhaynes/BinarySerializer#134]
Hi,

I'm trying to map a 3-bit number from data, to an integer in a POCO class - the value is scaled by some number (45 in my case). I've observed that `FieldScale` only works on doubles, and not integers - unfortunately.

Would it be feasible to support integers (and other types) for scales?

Thanks in advance :)

Mike.

**Comment by jefffhaynes** [comment]
Yup, fixed in 8.3.1 :)
