### ISSUE TITLE
Field Byte Length vs Field Bit Length

### ISSUE THREAD

**Issue by darren1713** [jefffhaynes/BinarySerializer#141]
https://github.com/jefffhaynes/BinarySerializer/blob/5b3b955422311758cf62fff8685d480300f86941/BinarySerializer/FieldLength.cs#L42

The base return value doesn't differentiate between bytes/bits. Ideally the base return value would be removed and force all references in the library to specifically get/set "ByteCount" and "BitCount". There are references in the library that mix bit/byte counts and will follow up with some updates for bit parsing.

**Comment by jefffhaynes** [comment]
I’m not sure I follow. What do you mean by the base return value?


________________________________

**Comment by darren1713** [comment]
Hi Jeff,

Throughout the all references using the FieldLength class need updated to differentiate bitcount vs bytecount. A quick example is if you set a field length of 7 bits, FieldLength returns a value of 7, which most/all of the code assumes is bytes. The FieldLength class for clarity should probably only return bits, and have a second property for bitsperbyte. Second option is to remove the get function and specifically request getbits or getbytes, but the issue there is something like 6 bits is not 1 byte. Does this help explain the issue? I can point out some references in the library that use the incorrect values if it helps, just writing some quick notes on mobile here. Cheers!

**Comment by jefffhaynes** [comment]
Sorry, this fell off my radar.  I honestly I have no idea if I fixed this or not but it looks to me like the FieldLength class deals with things in terms of bits and bytes exclusively but let me know if it's still confusing.
