### ISSUE TITLE
Correct way of getting parent value during deserialization.

### ISSUE THREAD

**Issue by mikedavison** [jefffhaynes/BinarySerializer#145]
I previously raised this in a complex way (see #88) but would like a more succinct answer.
Pseudo Code:

```
Class A {
   [FieldOrder(0)] 
    pubic int intOfA;
   [FieldOrder(1)]
    public B myB;
}
Class B {
   [Ignore]
   public A parent;
   [FieldOrder(0)]
   [SerializeWhen("intOfA",1)]
   public double intOfB;
}
```
As i understand your code during deserialization , it would construct A, read "`intOfA`", then construct B and conditionally read "`intOfB`.
My questions are:
1. How can I set `parent` field prior to deserializing B? Normally I would set this by calling the class constructor ( `public B(A parent) { this.parent = parent}` )
2. What is the correct way get the value of parent's  `intOfA` to test whether to deserialize `intOfB`?

**Comment by mikedavison** [comment]
Ok so I have a handle on how the application works and figured out how to do what I need in a round about way.  Lengthy description to help others.
in a nutshell there seems no way to set the `parent ` because the class object is only created after all of the data required is read from the deserializer. In the example above assuming no serializewhen , the sequence is:
1. serializer reads value of `intOfA`
2. serializer then reads value of `intOfB`
3. serializer creates class `B `object
4. serializer populates value of `intOfB` into class B object `B`
5. now it has both fields for A it creates class A and adds `intOfA `value and object `B`

So, this means that I cannot set `parent `field in `B `until after `A `has been created right at the end and this cannot be done in the confines of the serializer.

How did I get around my problem. I worked around some of the issues by using the serializer context feature. I still had to go over the objects and set parent references post deserialization.

-

**Comment by jefffhaynes** [comment]
Is intOfA something that is contained in the data source?  If not, then the only way to do this is to pass in a serialization context that specifies intOfA for a given deserialization operation.
