### ISSUE TITLE
Is it possible to get value from sibling?

### ISSUE THREAD

**Issue by mikedavison** [jefffhaynes/BinarySerializer#147]
```
Class Parent{
[FieldOrder(1)]  
public ClassA config
[FieldOrder(2)]
[FieldCount("ClassA.count", RelativeSourceMode = RelativeSourceMode.FindAncestor, AncestorType = typeof(ClassA))]
public List<ClassB> somelist
}
Class ClassA {
    public int count;
}
Class ClassB {
[FieldOrder(1)]
   public int XXX;
[FieldOrder(2)]
   public int YYY;
}
```
Sort of like above. I need to get a count from a sibling class in the parent structure. I have tried a number of ways and nothing works. Tried through relativesourcemode but that gives "No Ancestor Found" error.

**Comment by jefffhaynes** [comment]
You should be able to just use regular path binding for this.  Change "ClassA.count" to "config.count" and drop the rest:

`
[FieldCount("config.count")]
`

**Comment by jefffhaynes** [comment]
Closing this but please reopen if you need more help with it.
