### ISSUE TITLE
SerializeWhen Attributes And'd as opposed to OR'd?

### ISSUE THREAD

**Issue by jda808** [jefffhaynes/BinarySerializer#15]
Assume the following:

OrderAdditionalKegs only needs to be Serialized when PartyBusIsComing == true AND
ModelsAtPlayHouseMansion >= 20

```C#
[FieldOrder(0)]
public int ModelsAtPlayHouseMansionCount  {get; set;}
[FieldOrder(1)]
public bool PartyBusIsComing {get; set;}

[FieldOrder(2)]
[SerializeWhen("ModelsAtPlayHouseMansionCount", true, ConverterParameter = "20", ConverterType = typeof(GreaterOrEqualConverter))]
[SerializeWhen("PartyBusIsComing", true)]
public bool OrderAdditionalKegs {get; set;}

```

This will not work because SerializeWhen are always ||'d together. 
Can you show an example where a converter accepts more than one argument?

**Comment by jefffhaynes** [comment]
Can you invert the two conditions so they can be or'd instead of an'd?  In this case, I guess that would be to use an InvertingConverter on the PartyBusIsComing property and a LessThanConverter instead of a GreaterOrEqualConverter.

**Comment by jda808** [comment]
Yes. Just wanted to make sure I wasn't missing something.

**Comment by jefffhaynes** [comment]
No, I opted to keep it simple so currently there's no way to do 'and' or pass multiple parameters. 




    _____________________________

**Comment by jda808** [comment]
All good. I've caused enough headaches. Sorry for the static.

**Comment by jefffhaynes** [comment]
No worries, I appreciate the feedback!






On Thu, Apr 30, 2015 at 6:01 PM -0700, "jda808" <notifications@github.com> wrote:












All good. I've caused enough headaches. Sorry for the static.
