### ISSUE TITLE
Different behaviour of FieldCount and FiledLength on double array 

### ISSUE THREAD

**Issue by A016699** [jefffhaynes/BinarySerializer#156]
Hello, 
If I'm using the  FieldLength attribute for an double array the stream position after de-serialization is wrong. If I'm using the FieldCount the position is correct. 

Hier are the class I'm using :
```class TestProtocol
    {
        [FieldOrder(0)]
        public int Length { get; set; }
        [FieldOrder(10)]
        [FieldLength(nameof(Length))]
        public double[] Data { get; set; }
    }
```
If the Length Property = 10 the File position after reading should 84 but I'm getting 14 (am attached the small test program)
[Program.zip](https://github.com/jefffhaynes/BinarySerializer/files/5238571/Program.zip)

It also looks like that it is not working for float and long.

**Comment by jefffhaynes** [comment]
That's correct.  FieldLength refers to byte length, not array count.  I think you want FieldCount.

**Comment by A016699** [comment]
Thanks Jeff for clarifying. May you should explizit mention that at your documentation.
