### ISSUE TITLE
How to integrate Protobuf-net?

### ISSUE THREAD

**Issue by lOlbas** [jefffhaynes/BinarySerializer#166]
Hello!

I am trying to (de-)serialize classes that contain classes marked with `[ProtoContract]` as their fields. Here is an example base event:

```
public class ProtoBufRootEvent<T>
{
    public uint DataLength;
    
    public EventTypes OpCode;
    
    public T Data;
}
```

The generic part is determined by the value of `OpCode` field and does not have base class. Since this class is the only that will be used for serialization purposes, I need to get rid of `T`, right? So looking through the available attributes I found the subtype attribute and naturally went with this approach:

```
    // PingEvent and PongEvent classes are not marked with [ProtoContract]
    [FieldOrder(2)]
    [FieldLength(nameof(DataLength))]
    [Subtype(nameof(OpCode), EventTypes.Ping, typeof(PingEvent))]
    [Subtype(nameof(OpCode), EventTypes.Pong, typeof(PongEvent))]
    [SubtypeDefault(typeof(byte[]))]
    public object Data;
```

and was immediately greeted with [`"Deserializing object fields not supported."`](https://github.com/jefffhaynes/BinarySerializer/blob/7010214769ef8750026852fbb0e0f784b9372b16/BinarySerializer/Graph/ValueGraph/UnknownValueNode.cs#L64) error. However when using the `Subtype`-ish switch, I thought that the actual type could be determined with reflection.

Next thing I looked at were custom serialization via `IBinarySerializable` and inheriting `FieldValueAttributeBase`, but both seem to require specifying the `T` parameter to them in the end.

Here is the latest version I am trying to make work with the dirty workaround of declaring empty base class to use for all event classes:

```
public class ProtoBufEvent
{
    [FieldOrder(0)]
    public uint DataLength;
    
    [FieldOrder(1)]
    public EventTypes OpCode;
    
    [FieldOrder(2)]
    [FieldLength(nameof(DataLength))]
    [Subtype(nameof(OpCode), EventTypes.Ping, typeof(PingEvent))]
    [Subtype(nameof(OpCode), EventTypes.Pong, typeof(PongEvent))]
    [SubtypeDefault(typeof(Default))]
    public ProtoBase Data;
}

public class ProtoBase { }

public class PingEvent : ProtoBase
{
    [FieldOrder(3)]
    public uint Serial;
}

public class PongEvent : ProtoBase
{
    [FieldOrder(3)]
    public uint Serial;
    
    [FieldOrder(4)]
    public ulong Time;
}

public class Default : ProtoBase
{
    [FieldOrder(3)]
    public byte[] Bytes;
}
```

The approach above does work, since it is similar to the one in the examples, but this still does not solve the main problem: serialize ProtoBuf classes via the protobuf-net serializator. And in anyway, refactoring all event classes to inherit `ProtoBase` is not applicable.

For the sake of completeness, here is how Ping/Pong events would be described using protobuf:

```
[ProtoContract]
public class PingEvent
{
    [ProtoMember(1)]
    public uint Serial;
}

[ProtoContract]
public class PongEvent
{
    [ProtoMember(1)]
    public uint Serial;

    [ProtoMember(2)]
    public ulong Time;
}
```

I feel like it could be solved using [Custom Serialization](https://github.com/jefffhaynes/BinarySerializer#custom-serialization), but I can't get my head around it.

What I was thinking is is there an attribute which we can override and be able to check if the class field or field type have certain special attributes that will allow us to trigger their special (de)-serialization? Unless this feature is listed in the readme and I completely overlooked it.

Thanks

**Comment by jefffhaynes** [comment]
Yeah, the Subtype approach seems like the way to go and I agree the object thing seems a little over-restrictive.  There was a reason for it at one point in time but I might have fixed that and maybe it's just a leftover check now.  I'll look into it and see if it can be more forgiving.  In the mean time is there a reason you can't add a base class?

**Comment by jefffhaynes** [comment]
Ok, it sounds like you're saying adding a base class would just be a pain in the neck.  I do think this would arguably be a cleaner approach but I suppose object is technically a base class :)

**Comment by lOlbas** [comment]
@jefffhaynes `EventTypes` enum defines almost 800 opcodes, and more than 600 are represented as `ProtoContract` classes. Introducing a common base class is best avoided ☹️ So, you say it might be possible to use `object` as field type when using Subtype?

**Comment by jefffhaynes** [comment]
I think so.  Working on it now.

**Comment by jefffhaynes** [comment]
Just published in 8.6.  Take a look and let me know if it works for you.

**Comment by lOlbas** [comment]
@jefffhaynes awesome, works great with the `object` type 🙂 Although the main point of this issue still remains unsolved for me 😅  I still have troubles understanding how to properly apply Protobuf serializator as a replacement for BinarySerializer serializator.

Consider the following MVP:

```
using BinarySerialization;
using ProtoBuf;
using System;
using System.IO;

namespace Example166
{
    public enum EventTypes : ushort
    {
        Ping = 1,
        Pong = 2
    }

    [ProtoContract]
    public class PingEvent
    {
        [FieldOrder(1)]
        [ProtoMember(1)]
        public uint Serial;
    }

    [ProtoContract]
    public class PongEvent
    {
        [FieldOrder(1)]
        [ProtoMember(1)]
        public uint Serial;

        [FieldOrder(2)]
        [ProtoMember(2)]
        public ulong Time;
    }

    public class ProtoBufEvent
    {
        [FieldOrder(0)]
        public uint DataLength;

        [FieldOrder(1)]
        public EventTypes OpCode;

        [FieldOrder(2)]
        [FieldLength(nameof(DataLength))]
        [Subtype(nameof(OpCode), EventTypes.Ping, typeof(PingEvent))]
        [Subtype(nameof(OpCode), EventTypes.Pong, typeof(PongEvent))]
        [SubtypeDefault(typeof(byte[]))]
        public object Data;
    }

    internal class Program
    {
        private static void Main(string[] args)
        {
            // Ping event bytes via BinarySerializer:
            // 0x04 0x00 0x00 0x00, 0x01 0x00 0x01 0x02 0x03 0x04

            // Expected Ping event bytes via protobuf serialization:
            // 0x05 0x00 0x00 0x00 0x01 0x00 0x08 0x81 0x84 0x8C 0x20

            var pbEvent = new ProtoBufEvent
            {
                DataLength = 4,
                OpCode = EventTypes.Ping,
                Data = new PingEvent
                {
                    Serial = 67305985
                }
            };

            using (var stream = new MemoryStream())
            {
                new BinarySerializer().Serialize(stream, pbEvent);

                var sampleBytes = stream.ToArray();

                var pingEvent = new BinarySerializer().Deserialize(sampleBytes, typeof(ProtoBufEvent));

                Console.ReadLine();
            }
        }
    }
}
```

If I were to comment `FieldOrder` attributes in `PingEvent`, the program will throw an error because it can't serialize ProtoContract, obviously. How can I explicitly call protobuf serializer in this case?

**Comment by jefffhaynes** [comment]
Sorry, I don't know anything about the .net protobuf serializer.  Is the output from BinarySerializer incorrect?

**Comment by lOlbas** [comment]
@jefffhaynes the output from BinarySerializer serializes fields as regular values, whereas the field should be serialized using protobuf serializer. I was able to make it work using `IBinarySerializable`:

```
public class ProtoSerialize : IBinarySerializable
{
    [Ignore]
    public object Value { get; set; }

    public void Deserialize(Stream stream, Endianness endianness, BinarySerializationContext context)
    {
        var method = typeof(ProtoBuf.Serializer).GetMethods().FirstOrDefault(m => m.Name == "Deserialize" && m.GetParameters().Length == 1);
        var genericMethod = method?.MakeGenericMethod(context.Value.GetType());

        Value = genericMethod?.Invoke(null, new object[] { stream });
    }

    public void Serialize(Stream stream, Endianness endianness, BinarySerializationContext context)
    {
        var method = typeof(ProtoBuf.Serializer).GetMethods().FirstOrDefault(m => m.Name == "Serialize" && m.GetParameters().Length == 2);
        var genericMethod = method?.MakeGenericMethod(context.Value.GetType());

        genericMethod?.Invoke(null, new [] { stream, context.Value });
    }
}
```

and then using it like this:

```
public class PingEvent : ProtoSerialize { ... }

[FieldOrder(2)]
[FieldLength(nameof(DataLength))]
[Subtype(nameof(OpCode), EventTypes.Ping, typeof(PingEvent))]
[Subtype(nameof(OpCode), EventTypes.Pong, typeof(PongEvent))]
// [SubtypeDefault(typeof(byte[]))] // Obviously can no longer use default branch without extra default class
public ProtoSerialize ProtoData;
```

This solution has 2 major drawbacks:

1. Necessity to inherit the `ProtoSerialize` class for all types used in `[Subtype]`
2. New redundant field `Value` in all child classes.

IMO the way this can be implemented is:
1. Create new library class that inherits `IBinarySerializable`
2. This class will have field `Value` which will be used to set/read the field value within `Deserialize` and `Serialize` methods
3. Create user class that inherits new library class and use it in an attribute.

Here is how I imagine it:

```
public class NewBinarySerializable : IBinarySerializable
{
    [Ignore]
    public object Value { get; set; }
}

public class ProtoSerialize : NewBinarySerializable
{
    public void Deserialize(Stream stream, Endianness endianness, BinarySerializationContext context)
    {
        var method = typeof(ProtoBuf.Serializer).GetMethods().FirstOrDefault(m => m.Name == "Deserialize" && m.GetParameters().Length == 1);
        var genericMethod = method?.MakeGenericMethod(context.Value.GetType());

        Value = genericMethod?.Invoke(null, new object[] { stream });
    }

    public void Serialize(Stream stream, Endianness endianness, BinarySerializationContext context)
    {
        var method = typeof(ProtoBuf.Serializer).GetMethods().FirstOrDefault(m => m.Name == "Serialize" && m.GetParameters().Length == 2);
        var genericMethod = method?.MakeGenericMethod(context.Value.GetType());

        genericMethod?.Invoke(null, new [] { stream, context.Value });

        Value = context.Value;
    }
}

public class PingEvent { ... }

[FieldOrder(2)]
[FieldLength(nameof(DataLength))]
[Subtype(nameof(OpCode), EventTypes.Ping, typeof(PingEvent))]
[Subtype(nameof(OpCode), EventTypes.Pong, typeof(PongEvent))]
[SubtypeDefault(typeof(byte[]))] // Can use default branch again!
[SerializeWith(typeof(ProtoSerialize))]
public object ProtoData;
```

However this approach might not work with SubtypeFactory - I am still trying to make it work with the working MVP I have above

**Comment by jefffhaynes** [comment]
I would consider the custom serialization as a last resort.  Since I don't really know what the intended format is it's hard to say where the issue is.  Can you tell what isn't working with the subtype approach?  I know that protobuf uses variable length integers and the end of your byte array looks vaguely like a varint to me.  Is that the issue?  If so, I would recommend creating a varint custom object that implements IBinarySerializable.  I've actually done similar things in other projects.

**Comment by lOlbas** [comment]
@jefffhaynes what I try to achieve is defer serialization of `[ProtoContract]` classes to the protobuf library. They already properly handle it, why reinvent the wheel? 😄

My MVP above is based on this example, but Varuint is one of the many things Protobuf has 🤔

**Comment by jefffhaynes** [comment]
Ah, ok I understand now.  That's tricky :)

Custom serialization is probably your best bet although from a maintainability standpoint I would probably make it pure BinarySerializer or pure protobuf.  The hybrid approach might be tough.

Varuint isn't that bad, maybe just use the example!

**Comment by lOlbas** [comment]
@jefffhaynes a similar problem would be serializing dictionary field as JSON or XML string. I guess, it would also be tricky, right?

**Comment by lOlbas** [comment]
@jefffhaynes I've implement custom serialization in [this branch](https://github.com/lOlbas/BinarySerializer/commit/c76af68790d616669739f75ff21dcceb1b918d0a). It probably has some flaws that I missed, but I hope it will you an idea of how I imagined it working 🙂 

Testing this approach I also noticed lack of Dictionary serialization support (that I couldn't bypass elegantly), which seems like a perfect candidate for custom serialization, because I can't imagine serializing dictionaries not being a valid use-case 🤔
