### ISSUE TITLE
Add Kaitai Struct Compiler

### ISSUE THREAD

**Issue by mganss** [jefffhaynes/BinarySerializer#167]
First off, I love BinarySerializer. I found this while looking for an alternative to [Kaitai Struct](https://kaitai.io/) that can not only deserialize but also serialize. And although translating manually from the format description I have in Kaitai has worked nicely, it would be awesome to have a compiler that can generate BinarySerializer C# from .ksy. Kaitai has a C# backend but it can only deserialize (like all its backends AFAIK).

Kaitai has a collection of [format specifications](https://formats.kaitai.io/) that would immediately become available to BinarySerializer if a compiler existed.

**Comment by pgodwin** [comment]
To be clear, I don't speak for this project... but I'd imagine something like that either makes more sense as part of the Kaitai Compiler itself (eg a new Compiler based on the [existing C# implementation](https://github.com/kaitai-io/kaitai_struct_compiler/blob/master/shared/src/main/scala/io/kaitai/struct/languages/CSharpCompiler.scala)?), or as an external tool separate from BinarySerializer?

**Comment by jefffhaynes** [comment]
Yeah I have to agree with @pgodwin.  I think I prefer the loose coupling approach.  But it looks like a cool project!

**Comment by mganss** [comment]
Yes, absolutely. I'd imagine it as a separate tool (not a feature within the library) but it could still be a part of this project/repo and shipped as a [.NET global tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools).
