### ISSUE TITLE
Reverse Binding not allowed

### ISSUE THREAD

**Issue by mganss** [jefffhaynes/BinarySerializer#172]
I have the following class definition:

```c#
class Demo
{
    [FieldOrder(0)]
    public uint BodyCrc { get; set; }

    [FieldOrder(1)]
    [FieldCrc32(nameof(BodyCrc))]
    public uint Body { get; set; }
}
```

When trying to serialize I get
> InvalidOperationException: Reverse binding not allowed on FieldValue attributes.  Consider swapping source and target.

The file format I'm trying to serialize demands `BodyCrc` to come before `Body`. Is there an elegant way to do this?

**Comment by jefffhaynes** [comment]
Unfortunately no. The nature of the "serializer" is that one thing follows after the other. Recommend firing whomever wrote the format 😉

**Comment by mganss** [comment]
The pattern is part of the import/export format for a device from a big electronic equipment manufacturer. No docs of course, had to reverse engineer it 🙄
