### ISSUE TITLE
[FEATURE REQUEST] SerializeWhen comparer operator

### ISSUE THREAD

**Issue by sn4k3** [jefffhaynes/BinarySerializer#177]
Would be usefull to have operators on SerializeWhen or a new SerializeWhenCompare attribute

So, for example, i can have: **[SerializeWhenCompare (nameof(Version), Enum.GreaterThan, 2)]** which will be serialized when version is > than 2

Operators:

```
Enum.EqualTo
Enum.DifferentThan
Enum.LessThan
Enum.LessEqualThan
Enum.GreaterThan
Enum.GreaterEqualThan
...
```

**Comment by jefffhaynes** [comment]
Good idea
