### ISSUE TITLE
Add ability to load endianness from a variable

### ISSUE THREAD

**Issue by wpt-airbus** [jefffhaynes/BinarySerializer#18]
I can think of a few use cases where endianness is specificed within the format.  
I'd be awesome if endianness could be loaded from a variable!

**Comment by jefffhaynes** [comment]
I think you should be able to do that by subscribing to the memberdeserialized property and then switch the serializer global endianness. Sorry, don't have it in front of me I'm sitting on a plane. 



    _____________________________

**Comment by jefffhaynes** [comment]
Any luck with this?  I can send an example if you need it. 






On Wed, Jun 3, 2015 at 9:55 AM -0700, "wpt-airbus" <notifications@github.com> wrote:












I can think of a few use cases where endianness is specificed within the format.


I'd be awesome if endianness could be loaded from a variable!

**Comment by wpt-airbus** [comment]
Jeff,

Yes, thank you for the advice!  Your input definitely made the difference
in me pursuing this library.

I have run into another use-case that has me scratching my head.  Your
advice was so spot on before, I'd sure appreciate if you could suggest a
best tactic on handling this!

I have an array of byte arrays, each of a different size.  The count and
sizes of each object aren't stored in an ancestor, but in a sibling.
Here's my pseudo-layout:

class file
   class header
      int object_count
      int[] object_byte_lengths
   class body
      byte[][] objects

So far I think your library is fantastic - I was able to do in an afternoon
what might have taken me three days by conventional parsing.  I hope that
me sharing my use cases is a net positive to you, and not a hassle.


Cheers!

Bill Thorp

On Thu, Jun 4, 2015 at 5:56 PM, Jeff Haynes <notifications@github.com>
wrote:

> Any luck with this?  I can send an example if you need it.
>
>
>
>
>
>
>
> On Wed, Jun 3, 2015 at 9:55 AM -0700, "wpt-airbus" <
> notifications@github.com> wrote:
>
>
>
>
>
>
>
>
>
>
>
>
> I can think of a few use cases where endianness is specificed within the
> format.
>
>
> I'd be awesome if endianness could be loaded from a variable!
>
>
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/BinarySerializer/issues/18#issuecomment-109098609>
> .
>



-- 
Bill Thorp
Senior Solutions Architect
RGS, Responsive Geospatial Systems, LLC
213 Linden Street 3rd Floor
Fort Collins, CO 80524 USA

Phone: 970.372.5555
Direct: 970.372.5561
Mobile: 850.222.3266

-- 
 This e-mail and any files transmitted with it are the property of RGS and 
are intended solely for the use of the individual or entity to whom this 
e-mail is addressed. If you are not one of the named recipient(s) or 
otherwise have reason to believe that you have received this message in 
error, please notify the sender at 1-970-372-5555 and delete this message 
immediately from your computer. Any other use, retention, dissemination, 
forwarding, printing, or copying of this e-mail is strictly prohibited. 
This email is subject to storage and review by RGS LLC. Thanks for your 
cooperation!

**Comment by jefffhaynes** [comment]
Great, glad to hear it!

Definitely an interesting use case and I'm not sure offhand how to support
it.  The answer may be that at some point a format becomes "too relational"
and isn't really serialization anymore but feels more like a database or
something akin to that.  One thing I think might be missing from the
serializer is an indexer syntax wherein you can bind to specific elements
in an array (something like "Class.Items[1]").  However, in your case I
don't think adding that would solve this as it isn't a matter of indexing a
specific item but a relative item.

Let me mull it over and get back to you.

Thanks


On Fri, Jun 5, 2015 at 12:13 PM, wpt-airbus <notifications@github.com>
wrote:

> Jeff,
>
> Yes, thank you for the advice! Your input definitely made the difference
> in me pursuing this library.
>
> I have run into another use-case that has me scratching my head. Your
> advice was so spot on before, I'd sure appreciate if you could suggest a
> best tactic on handling this!
>
> I have an array of byte arrays, each of a different size. The count and
> sizes of each object aren't stored in an ancestor, but in a sibling.
> Here's my pseudo-layout:
>
> class file
> class header
> int object_count
> int[] object_byte_lengths
> class body
> byte[][] objects
>
> So far I think your library is fantastic - I was able to do in an afternoon
> what might have taken me three days by conventional parsing. I hope that
> me sharing my use cases is a net positive to you, and not a hassle.
>
>
> Cheers!
>
> Bill Thorp
>
> On Thu, Jun 4, 2015 at 5:56 PM, Jeff Haynes <notifications@github.com>
> wrote:
>
> > Any luck with this? I can send an example if you need it.
> >
> >
> >
> >
> >
> >
> >
> > On Wed, Jun 3, 2015 at 9:55 AM -0700, "wpt-airbus" <
> > notifications@github.com> wrote:
> >
> >
> >
> >
> >
> >
> >
> >
> >
> >
> >
> >
> > I can think of a few use cases where endianness is specificed within the
> > format.
> >
> >
> > I'd be awesome if endianness could be loaded from a variable!
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jefffhaynes/BinarySerializer/issues/18#issuecomment-109098609
> >
> > .
> >
>
>
>
> --
> Bill Thorp
> Senior Solutions Architect
> RGS, Responsive Geospatial Systems, LLC
> 213 Linden Street 3rd Floor
> Fort Collins, CO 80524 USA
>
> Phone: 970.372.5555
> Direct: 970.372.5561
> Mobile: 850.222.3266
>
> --
> This e-mail and any files transmitted with it are the property of RGS and
> are intended solely for the use of the individual or entity to whom this
> e-mail is addressed. If you are not one of the named recipient(s) or
> otherwise have reason to believe that you have received this message in
> error, please notify the sender at 1-970-372-5555 and delete this message
> immediately from your computer. Any other use, retention, dissemination,
> forwarding, printing, or copying of this e-mail is strictly prohibited.
> This email is subject to storage and review by RGS LLC. Thanks for your
> cooperation!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/BinarySerializer/issues/18#issuecomment-109347153>
> .
>



-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery

**Comment by jefffhaynes** [comment]
After thinking about it I think this probably makes sense but it's going to take some doing.  Give me a little time to work on it.

**Comment by jefffhaynes** [comment]
If you want to check it out, I added the ability to bind to enumerable sources to the jagged_array branch (https://github.com/jefffhaynes/BinarySerializer/tree/jagged_array).  This means you can do:

```c#
    public class JaggedArrayClass
    {
        [FieldOrder(0)]
        public int ArrayCount { get; set; }

        [FieldOrder(1)]
        [FieldCount("ArrayCount")]
        public int[] ArrayLengths { get; set; }

        [FieldOrder(2)]
        [FieldCount("ArrayCount")]
        [ItemLength("ArrayLengths")]
        public byte[][] Arrays { get; set; }
    }
```

I want to check a few things before I merge it into master and push it to nuget but feel free to play if you want and let me know if it works for you.

**Comment by jefffhaynes** [comment]
Jagged array support is in 4.3.
