### ISSUE TITLE
Proper usage of Value Converter

### ISSUE THREAD

**Issue by Ruslebiffen** [jefffhaynes/BinarySerializer#19]
I may have misunderstood how to use a value converter during serialization. I have a field that should be serialized to a UInt, but deserialized to a DateTime.

I have a class that is defined like so:

1)

	public class ValueUpdateMessage
	{
		[FieldOrder(0)]
		public UInt TimeStamp { get; set; }
		
		[FieldOrder(1)]
		public byte NewValue { get; set; }
	}

Since I am working with .Net and DateTime, I would like to change my representation of the message to

2)

	public class ValueUpdateMessage
	{
		[FieldOrder(0)]
		public DateTime TimeStamp { get; set; }
		
		[FieldOrder(1)]
		public byte NewValue { get; set; }
	}
since that makes date times easier to work with. As of now, I can achieve this by introducing an extra member:

3)

    public class ValueUpdateMessage
	{
		[Ignore]
		public DateTime TimeStamp 
		{
			get { return ConvertToDateTime(UnixTimeStamp); }
			set { UnixTimeStamp = ConvertToUnixTime(value); }
		}
		
		[FieldOrder(0)]
		public DateTime UnixTimeStamp { get; set; }
		
		[FieldOrder(1)]
		public byte NewValue { get; set; }
	}

However, it would be a lot cleaner to use the class as defined in `2`. I saw the example with a value converter in the Readme, but I can't get it to work. The FieldOrder attribute does not have the ConverterType field, so I tried using one of the others, such as 
`[FieldOffset(0, ConverterType = typeof(DateTimeToUnixTimestampConverter)]`, and 
`[FieldLength(4, ConverterType = typeof(DateTimeToUnixTimestampConverter)]`

Is there a straight forward way to do this?

**Comment by jefffhaynes** [comment]
Unfortuantely the value converter applies to the field *binding*, not the
field value although I definitely see your confusion.  Maybe it should be
called the binding converter!  Let me mull it over but I don't think
there's a straightforward way other than what you're doing.

On Thu, Jun 11, 2015 at 9:40 AM, Ruslebiffen <notifications@github.com>
wrote:

> I may have misunderstood how to use a value converter during
> serialization. I have a field that should be serialized to a UInt, but
> deserialized to a DateTime.
>
> I have a class that is defined like so:
>
> 1)
>
> public class ValueUpdateMessage
> {
>     [FieldOrder(0)]
>     public UInt TimeStamp { get; set; }
>
>     [FieldOrder(1)]
>     public byte NewValue { get; set; }
> }
>
> Since I am working with .Net and DateTime, I would like to change my
> representation of the message to
>
> 2)
>
> public class ValueUpdateMessage
> {
>     [FieldOrder(0)]
>     public DateTime TimeStamp { get; set; }
>
>     [FieldOrder(1)]
>     public byte NewValue { get; set; }
> }
>
> since that makes date times easier to work with. As of now, I can achieve
> this by introducing an extra member:
>
> 3)
>
> public class ValueUpdateMessage
> {
>     [Ignore]
>     public DateTime TimeStamp
>     {
>         get { return ConvertToDateTime(UnixTimeStamp); }
>         set { UnixTimeStamp = ConvertToUnixTime(value); }
>     }
>
>     [FieldOrder(0)]
>     public DateTime UnixTimeStamp { get; set; }
>
>     [FieldOrder(1)]
>     public byte NewValue { get; set; }
> }
>
> However, it would be a lot cleaner to use the class as defined in 2. I
> saw the example with a value converter in the Readme, but I can't get it to
> work. The FieldOrder attribute does not have the ConverterType field, so I
> tried using one of the others, such as
> [FieldOffset(0, ConverterType = typeof(DateTimeToUnixTimestampConverter)],
> and
> [FieldLength(4, ConverterType = typeof(DateTimeToUnixTimestampConverter)]
>
> Is there a straight forward way to do this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/BinarySerializer/issues/19>.
>



-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery
