### ISSUE TITLE
Exceptions not forwarded in DeserializeAsync

### ISSUE THREAD

**Issue by A016699** [jefffhaynes/BinarySerializer#195]
Hi, 
 I just want do switch to async methods. But the DeserializeAsync method does not forwarded any exception. 
I'm using a network stream and does not get any of the socket exceptions. As I saw you not awaiting all async method calls, is this may the issue as exceptions just forwarded if an async method is awaited.

**Comment by jefffhaynes** [comment]
Can you give me an example of what you're seeing?  And where are you seeing async calls that are not awaited?

**Comment by jefffhaynes** [comment]
Duplicate of #182
