### ISSUE TITLE
Non-generic Deserialize

### ISSUE THREAD

**Issue by Ruslebiffen** [jefffhaynes/BinarySerializer#20]
I'm not that familiar with git and github, so I was unsure how to create a pull request. 

I found that it was needed to call a non-generic Deserialize() in my code. This could be solved by adding this to BinarySerializer.cs:

        public object Deserialize(Stream stream, Type type, object context = null)
        {
            RootTypeNode graph = GetGraph(type);

            var serializer = (ContextValueNode)graph.CreateSerializer(null);
            serializer.EndiannessCallback = () => Endianness;
            serializer.EncodingCallback = () => Encoding;
            serializer.Context = context;
            serializer.Deserialize(new StreamLimiter(stream), _eventShuttle);

            return serializer.Value;
        }

and change the existing methods to this: 
  
        public T Deserialize<T>(Stream stream, object context = null)
        {
            return (T) Deserialize(stream, typeof(T), context);
        }

        public T Deserialize<T>(byte[] data, object context = null)
        {
            return (T)Deserialize(new MemoryStream(data), typeof (T), context);
        }

**Comment by jefffhaynes** [comment]
Sure, can I ask what your use case is for a non-generic version?

**Comment by Ruslebiffen** [comment]
There might be better ways to accomplish what I was doing, but I had a series of different classes who implemented an interface

    public interface IRequest
    {
        Type ResponseType { get; }
    }

So I knew what type the returned object would be based on this property in the object, and could then use the ResponseType property to deserialize it

    var request = new SomeRequest() // object which implements IRequest
    byte[] receivedData = myNetworkService.SendRequest(request.Serialize());
    var response = binarySerializer.Deserialize(receivedData, request.ResponseType);

This would of course just give me an `object` which I would need to cast later, but in this piece of code that sends the request and returns the response, it was handy. 

Don't know if you could accomplish something similar with generics? I found no way to use the ResponseType property without reflection and stuff.

**Comment by jefffhaynes** [comment]
No, I think what you're suggesting probably makes sense and I figured it was something along those lines. Let me play with it and see. 
Thanks,
Jeff






On Thu, Oct 15, 2015 at 2:39 AM -0700, "Ruslebiffen" <notifications@github.com> wrote:












There might be better ways to accomplish what I was doing, but I had a series of different classes who implemented an interface

public interface IRequest
{
    Type ResponseType { get; }
}




So I knew what type the returned object would be based on this property in the object, and could then use the ResponseType property to deserialize it

var request = new SomeRequest() // object which implements IRequest
byte[] receivedData = myNetworkService.SendRequest(request.Serialize());
var response = binarySerializer.Deserialize(receivedData, request.ResponseType);




This would of course just give me an object which I would need to cast later, but in this piece of code that sends the request and returns the response, it was handy. 



Don't know if you could accomplish something similar with generics? I found no way to use the ResponseType property without reflection and stuff.

**Comment by jefffhaynes** [comment]
Sorry for the delay in this; your feature is available in 4.4.1 on nuget.  Thanks!
