### ISSUE TITLE
SubtypeAttribute seems not to work

### ISSUE THREAD

**Issue by Anhaltiner0708** [jefffhaynes/BinarySerializer#24]
[MySource.txt](https://github.com/jefffhaynes/BinarySerializer/files/98887/MySource.txt)
[exceptionWhileSerialize.txt](https://github.com/jefffhaynes/BinarySerializer/files/98889/exceptionWhileSerialize.txt)
[exceptionWhileDeserialize.txt](https://github.com/jefffhaynes/BinarySerializer/files/98890/exceptionWhileDeserialize.txt)

```C#
 public enum LoadCarrierType
    {
        /// <summary>
        /// unknown
        /// </summary>
        Unknown = 0, 

        /// <summary>
        /// bin 1
        /// </summary>
        Bin1 = 1, 

        /// <summary>
        /// bin 2
        /// </summary>
        Bin2 = 2, 

        /// <summary>
        /// palette
        /// </summary>
        Palette = 3, 

        /// <summary>
        /// pipe
        /// </summary>
        Pipe = 4
    }

public class LoadCarrierData
    {
        #region constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="LoadCarrierData"/> class.
        /// </summary>
        public LoadCarrierData()
        {
        }

        #endregion

        #region public properties  

        /// <summary>
        /// Gets or sets type of the load carrier
        /// </summary>
        [FieldOrder(0)]
        [SerializeAs(SerializedType = SerializedType.UInt4)]
        public LoadCarrierType CarrierType { get; set; }

        /// <summary>
        /// Gets or Sets the data
        /// </summary>
        [FieldOrder(1)]
        [Subtype("CarrierType", LoadCarrierType.Unknown, typeof(object))]
        [Subtype("CarrierType", LoadCarrierType.Bin1, typeof(Bin1Data))]
        [Subtype("CarrierType", LoadCarrierType.Bin2, typeof(Bin2Data))]
        [Subtype("CarrierType", LoadCarrierType.Palette, typeof(PalData))]
        [Subtype("CarrierType", LoadCarrierType.Pipe, typeof(PipeData))]
        public object Data { get; set; }

        #endregion
    }
```

I have defined a class that holds different objects in the property Data. See attached file MySource.txt. I use the SubtypeAttribute and have defined the different objects. That leads to exception during serialization and derserialization. 

Is there something wrong in my class defintion? Please keep me informed!

Regards
Dirk (@Anhaltiner0708)

**Comment by jefffhaynes** [comment]
Since I don't have all the code it's hard to say for sure, but it seems likely that your "object" subtype is causing the problem.  Can you try removing this line?

```c#
[Subtype("CarrierType", LoadCarrierType.Unknown, typeof(object))]
```

If the CarrierType is Unknown then the Data field will be left as null.

**Comment by Anhaltiner0708** [comment]
I have remove this "object" subtype. But the serialization ends with the same exception.

**Comment by jefffhaynes** [comment]
Ok, I see it now.  I'll have to see if I can fix it, but if you can make your subtypes (Bin1Data, Bin2Data, PalData, and PipeData) derive from a common base class (i.e. CarrierData), and change your Data field to that type, it should work.  For example:

```c#
public CarrierData Data { get; set; }
```

Currently the framework doesn't support using "object" as a common base.

**Comment by jefffhaynes** [comment]
Let me know if that works for you. I'll also take a look at whether object can be supported as a common base.

**Comment by Anhaltiner0708** [comment]
Yes it works fine. Thank You!
