### ISSUE TITLE
CoreClr Update?

### ISSUE THREAD

**Issue by jda808** [jefffhaynes/BinarySerializer#26]
Any interest in getting this up and running with rc2*? Appears to take lots of jumping through hoops in the reflection namespace.

**Comment by jefffhaynes** [comment]
Yeah, definitely. I think I have at least some of the work done although I'm still learning. Take a look at the "universal" branch and let me know what you think. Still struggling with some things like how to package as nuget. 






On Thu, Jan 21, 2016 at 10:14 PM -0800, "Jason Adams" <notifications@github.com> wrote:












Any interest in getting this up and running with rc2*? Appears to take lots of jumping through hoops in the reflection namespace

**Comment by jda808** [comment]
Def a lot of learning here as well. Lot of confusion on portability. My rough understanding is BCL is not CoreCLR, and as such the targets need to be appended or modified.

Out of the box I am able to build the Universal branch via VS.net 2015. 
If I try via msbuild it fails. 
If I try to build via dnx (via osx) it fails. 
It I try building it against 4.6.1 and Asp.Net Core5 in vs.net 2015, it fails.

I don't know if I am barking up the wrong tree, but it looks there are going to have to be quite a few ifdefs when handling delegate creation via reflection methods. I was able to hack and get it to build but I'm not fully comfortable I understand the ramifications of what I did and not really sure how to test/verify everything is doing what it should be. Let me know if you want me to send a pull request.


Severity	Code	Description	Project	File	Line	Project Rank	Suppression State
Error	CS1061	'Type' does not contain a definition for 'IsPrimitive' and no extension method 'IsPrimitive' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\ArrayTypeNode.cs	28	1	Active
Error	CS0030	Cannot convert type 'System.Attribute' to 'T'	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\ReflectionExtensionMethods.cs	10	1	Active
Error	CS0117	'Delegate' does not contain a definition for 'CreateDelegate'	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\MagicMethods.cs	33	1	Active
Error	CS0117	'Delegate' does not contain a definition for 'CreateDelegate'	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\MagicMethods.cs	63	1	Active
Error	CS1061	'Type' does not contain a definition for 'IsEnum' and no extension method 'IsEnum' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\ContainerTypeNode.cs	73	1	Active
Error	CS1061	'Type' does not contain a definition for 'IsPrimitive' and no extension method 'IsPrimitive' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\ListTypeNode.cs	32	1	Active
Error	CS1061	'Type' does not contain a definition for 'IsAbstract' and no extension method 'IsAbstract' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\ObjectTypeNode.cs	51	1	Active
Error	CS1061	'Type' does not contain a definition for 'BaseType' and no extension method 'BaseType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\ObjectTypeNode.cs	170	1	Active
Error	CS1061	'Type' does not contain a definition for 'BaseType' and no extension method 'BaseType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\ObjectTypeNode.cs	172	1	Active
Error	CS1061	'Type' does not contain a definition for 'IsPrimitive' and no extension method 'IsPrimitive' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\TypeNode.cs	291	1	Active
Error	CS1061	'Type' does not contain a definition for 'IsAbstract' and no extension method 'IsAbstract' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\Graph\ValueGraph\ObjectValueNode.cs	66	1	Active
Error	CS1061	'Type' does not contain a definition for 'IsAbstract' and no extension method 'IsAbstract' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\Graph\ValueGraph\ObjectValueNode.cs	183	1	Active
Error	CS1061	'Type' does not contain a definition for 'IsPrimitive' and no extension method 'IsPrimitive' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs	269	1	Active
Error	CS1061	'Type' does not contain a definition for 'IsEnum' and no extension method 'IsEnum' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs	279	1	Active
Error	CS1061	'Type' does not contain a definition for 'IsPrimitive' and no extension method 'IsPrimitive' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)	BinarySerializer	C:\git\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs	279	1	Active

**Comment by jefffhaynes** [comment]
Cool, very interesting. I guess the thing I'm confused about is some of the errors seem to ref Type methods like IsEnum, IsPrimitive, etc. If I'm not mistaken those should be migrated to TypeInfo in the universal branch. Any chance you're building master?  Or are there #defines in universal and I'm just forgetting about it (on my phone). 






On Fri, Jan 22, 2016 at 12:53 PM -0800, "Jason Adams" <notifications@github.com> wrote:












Def a lot of learning here as well. Lot of confusion on portability. My rough understanding is BCL is not CoreCLR, and as such the targets need to be appended or modified.



Out of the box I am able to build the Universal branch via VS.net 2015. 

If I try via msbuild it fails. 

If I try to build via dnx (via osx) it fails. 

It I try building it against 4.6.1 and Asp.Net Core5 in vs.net 2015, it fails.



I don't know if I am barking up the wrong tree, but it looks there are going to have to be quite a few ifdefs when handling delegate creation via reflection methods. I was able to hack and get it to build but I'm not fully comfortable I understand the ramifications of what I did and not really sure how to test/verify everything is doing what it should be. Let me know if you want me to send a pull request.



Severity    Code    Description Project File    Line    Project Rank    Suppression State

Error   CS1061  'Type' does not contain a definition for 'IsPrimitive' and no extension method 'IsPrimitive' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?) BinarySerializer    C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\ArrayTypeNode.cs   28  1   Active

Error   CS0030  Cannot convert type 'System.Attribute' to 'T'   BinarySerializer    C:\git\BinarySerializer\BinarySerializer\ReflectionExtensionMethods.cs  10  1   Active

Error   CS0117  'Delegate' does not contain a definition for 'CreateDelegate'   BinarySerializer    C:\git\BinarySerializer\BinarySerializer\MagicMethods.cs    33  1   Active

Error   CS0117  'Delegate' does not contain a definition for 'CreateDelegate'   BinarySerializer    C:\git\BinarySerializer\BinarySerializer\MagicMethods.cs    63  1   Active

Error   CS1061  'Type' does not contain a definition for 'IsEnum' and no extension method 'IsEnum' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)   BinarySerializer    C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\ContainerTypeNode.cs   73  1   Active

Error   CS1061  'Type' does not contain a definition for 'IsPrimitive' and no extension method 'IsPrimitive' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?) BinarySerializer    C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\ListTypeNode.cs    32  1   Active

Error   CS1061  'Type' does not contain a definition for 'IsAbstract' and no extension method 'IsAbstract' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)   BinarySerializer    C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\ObjectTypeNode.cs  51  1   Active

Error   CS1061  'Type' does not contain a definition for 'BaseType' and no extension method 'BaseType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)   BinarySerializer    C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\ObjectTypeNode.cs  170 1   Active

Error   CS1061  'Type' does not contain a definition for 'BaseType' and no extension method 'BaseType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)   BinarySerializer    C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\ObjectTypeNode.cs  172 1   Active

Error   CS1061  'Type' does not contain a definition for 'IsPrimitive' and no extension method 'IsPrimitive' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?) BinarySerializer    C:\git\BinarySerializer\BinarySerializer\Graph\TypeGraph\TypeNode.cs    291 1   Active

Error   CS1061  'Type' does not contain a definition for 'IsAbstract' and no extension method 'IsAbstract' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)   BinarySerializer    C:\git\BinarySerializer\BinarySerializer\Graph\ValueGraph\ObjectValueNode.cs    66  1   Active

Error   CS1061  'Type' does not contain a definition for 'IsAbstract' and no extension method 'IsAbstract' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)   BinarySerializer    C:\git\BinarySerializer\BinarySerializer\Graph\ValueGraph\ObjectValueNode.cs    183 1   Active

Error   CS1061  'Type' does not contain a definition for 'IsPrimitive' and no extension method 'IsPrimitive' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?) BinarySerializer    C:\git\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs  269 1   Active

Error   CS1061  'Type' does not contain a definition for 'IsEnum' and no extension method 'IsEnum' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)   BinarySerializer    C:\git\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs  279 1   Active

Error   CS1061  'Type' does not contain a definition for 'IsPrimitive' and no extension method 'IsPrimitive' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?) BinarySerializer    C:\git\BinarySerializer\BinarySerializer\Graph\ValueGraph\ValueNode.cs  279 1   Active

**Comment by jefffhaynes** [comment]
Hey, I actually responded to this a few days ago but it looks like it didn't go through or something. Anyway looking at the errors it doesn't look like the universal branch to me. Is there any chance your building the master branch?

**Comment by jefffhaynes** [comment]
Ugh, *you're

**Comment by jda808** [comment]
yes, it looks like the output I copied from vs.net was indeed the master branch.

Assuming I switch to  universal branch, do I only need to build BinarySerializer.Unified?

**Comment by jefffhaynes** [comment]
Yes, I believe so (sorry, don't have it in front of me at the moment).

On Tue, Jan 26, 2016 at 3:03 PM, Jason Adams <notifications@github.com>
wrote:

> yes, it looks like the output I copied from vs.net was indeed the master
> branch.
>
> Assuming I switch to universal branch, do I only need to build
> BinarySerializer.Unified?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/BinarySerializer/issues/26#issuecomment-175202977>
> .
>



-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery

**Comment by jda808** [comment]
Looks like some good work has been done! Cheers.

Sorry if this doesn't make sense, but on universal branch, for DNX core build, are you BinarySerializer.Unified or BinarySerializer.Dotnet as your reference?

**Comment by jefffhaynes** [comment]
Actually BinarySerializer is the DNX folder now under the universal branch.  I think it's close, but I think I need to update unit testing still. I'm at Build right now and despite them shedding some light on all of this it's still pretty confusing. 






On Fri, Apr 1, 2016 at 9:10 AM -0700, "Jason Adams" <notifications@github.com> wrote:












Looks like some good work has been done! Cheers.



Sorry if this doesn't make sense, but on universal branch, for DNX core build, are you BinarySerializer.Unified or BinarySerializer.Dotnet as your reference?

**Comment by jda808** [comment]
Confusion is rampant! 

I'm doing clean clones from source trying to poke around blindly on Os X. Something new I noticed is that whatever you have done in BinarySerializer.BinarySerializer (the current dir you just mentioned) auto-magically changes .dnx config to compile against CoreCLR runtime... which will ultimately be good, but currently is bad because of corefx dependencies?!? Does one bootstrap on OSX?  i'm beyond clueless.

**Comment by jefffhaynes** [comment]
Hm. Are you saying you don't have corefx on OS X?  I'm afraid I know next to nothing about that...






On Fri, Apr 1, 2016 at 9:31 AM -0700, "Jason Adams" <notifications@github.com> wrote:












Confusion is rampant! 



I'm doing clean clones from source trying to poke around blindly on Os X. Something new I noticed is that whatever you have done in BinarySerializer.BinarySerializer (the current dir you just mentioned) auto-magically changes .dnx config to compile against CoreCLR runtime... which will ultimately be good, but currently is bad because of corefx dependencies?!? Does one bootstrap on OSX?  i'm beyond clueless.

**Comment by jda808** [comment]
Correct. FWIW, I now have to explicitly switch my run time prior to restore/build (the missing corefx is expected on my end).

**Comment by jefffhaynes** [comment]
This is what I don't understand. It should be able to target both I think but I don't know how to build that package. 






On Fri, Apr 1, 2016 at 9:37 AM -0700, "Jason Adams" <notifications@github.com> wrote:












Correct. FWIW, I now have to explicitly switch my run time prior to restore/build (the missing corefx is expected on my end).

**Comment by jefffhaynes** [comment]
But it did run on OSX?  That's neat...






On Fri, Apr 1, 2016 at 9:37 AM -0700, "Jason Adams" <notifications@github.com> wrote:












Correct. FWIW, I now have to explicitly switch my run time prior to restore/build (the missing corefx is expected on my end).

**Comment by jda808** [comment]
I've got a very basic and informal web api hosted on OS X and it's referencing the BS assembly (via project not nuget restore). It builds, it doesn't bomb out. 

Wiring up unit test framework is a different story though :-S
