### ISSUE TITLE
Deserialization stops before the object is completely

### ISSUE THREAD

**Issue by Anhaltiner0708** [jefffhaynes/BinarySerializer#27]
In the event that the stream is too short to fully serialize the object, an object is returned. The missing properties have values that have been assigned by the constructor.

In this case I expect any exception or the result is null. 

Is there a way to verify that all properties have been read from Stream?

example class
```C#
    public class LoadCarrierData
    {
        #region constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="LoadCarrierData"/> class.
        /// </summary>
        public LoadCarrierData()
        {
        }
        #endregion

        #region public properties  

        [FieldOrder(0)]
        [SerializeAs(SerializedType = SerializedType.UInt4)]
        public uint Prop1 { get; set; }

        [FieldOrder(1)]
        [SerializeAs(SerializedType = SerializedType.UInt1)]
        public byte Prop2 { get; set; }

        [FieldOrder(2)]
        [SerializeAs(SerializedType = SerializedType.UInt1)]
        public byte Prop3 { get; set; }

        [FieldOrder(3)]
        [SerializeAs(SerializedType = SerializedType.UInt4)]
        public uint Prop4 { get; set; }
        #endregion
    }
```

test method
```C#
        public void DeserializeInvalidMessageLittleEndian()
        {
            var serializer = new BinarySerializer() { Endianness = Endianness.Little };
            var inBytes = new byte[] { 0x01, 0x00, 0x00, 0x00, 0x40, 0x34 };
            
            using (var stream = new MemoryStream(inBytes))
            {
                try
                {
                    var actualObj = serializer.Deserialize<LoadCarrierData>(stream);
                    Assert.AreEqual(null, actualObj, "Deserialization done with invalid Stream.");
                }
                catch (InvalidOperationException ex)
                {
                    //Expected System.IO.EndOfStreamException or System.InvalidOperationException
                    this.TestContext.WriteLine(ex.ToString());
                }
            }
        }
```

**Comment by jefffhaynes** [comment]
Yes, my intent was to allow this during deserialization but it doesn't really make sense for non-nullable objects.  I've fixed this in 4.6.3 so you'll get an EndOfStreamException if the serializer encounters a non-nullable type (such as in your example) after the end of stream.  However, nullable types will still be allowed, and will be returned as null.  Thanks.

**Comment by jefffhaynes** [comment]
Greetings.  I've been looking at some behavior in a different project and I realized it may be better in general to return null where possible rather than throw an EndOfStreamException.  Would you be ok if in this example it simply returned null if it can't deserialize the entire object correctly?  This would allow it to continue if the object is part of a larger object graph that may overall be correct (but in the case where this object is, for example, length limited).  Definitely open to thoughts...

Thanks

**Comment by Anhaltiner0708** [comment]
Hello Jeff,

any thanks for this information. But we don't use your components any more. There was some updates in the past, that were not downward compatible. So we have to spent to many time to solve that. We has decided to develop and use our own components.

Cheers
Dirk

**Comment by jefffhaynes** [comment]
I understand. Yes, it took me too long to reach a stable model for the framework and fullly understand the nuances. Thanks for the feedback. 

---------------
I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses - Johannes Kepler




On Mon, Jan 9, 2017 at 12:58 AM -0500, "Anhaltiner0708" <notifications@github.com> wrote:












Hello Jeff,


any thanks for this information. But we don't use your components any more. There was some updates in the past, that were not downward compatible. So we have to spent to many time to solve that. We has decided to develop and use our own components.


Cheers

Dirk
