### ISSUE TITLE
No bytes will be return from serialization

### ISSUE THREAD

**Issue by Anhaltiner0708** [jefffhaynes/BinarySerializer#29]
From the serialization of the following object no bytes are written to the stream. What is wrong?

Object that should serialized
```C#
new LoadCarrierData(LoadCarrierType.Unknown, null);
```
I expect that two bytes (0x00, 0x00) are written to the stream! 

```C#
 public enum LoadCarrierType
    {
        /// <summary>
        /// unknown
        /// </summary>
        Unknown = 0, 

        /// <summary>
        /// bin 1
        /// </summary>
        Bin1 = 1, 

        /// <summary>
        /// bin 2
        /// </summary>
        Bin2 = 2, 

        /// <summary>
        /// palette
        /// </summary>
        Palette = 3, 

        /// <summary>
        /// pipe
        /// </summary>
        Pipe = 4
    }

public class LoadCarrierData
    {
    
        #region constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="LoadCarrierData"/> class.
        /// </summary>
        public LoadCarrierData()
            : this(LoadCarrierType.Unknown, null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoadCarrierData"/> class.
        /// </summary>
        /// <param name="carrierType">
        /// The carrier Type.
        /// </param>
        /// <param name="data">
        /// The data.
        /// </param>
        public LoadCarrierData(LoadCarrierType carrierType, BaseCarrierData data)
            : base()
        {
            this.CarrierType = carrierType;
            this.Data = data;
        }

        #endregion

        #region public properties  

        /// <summary>
        /// Gets or sets type of the load carrier
        /// </summary>
        [FieldOrder(0)]
        [SerializeAs(SerializedType = SerializedType.UInt2)]
        public LoadCarrierType CarrierType { get; private set; }

        /// <summary>
        /// Gets or Sets the data
        /// </summary>
        [FieldOrder(1)]
        [Subtype("CarrierType", LoadCarrierType.Unknown, typeof(BaseCarrierData))]
        [Subtype("CarrierType", LoadCarrierType.Bin1, typeof(Bin1Data))]
        [Subtype("CarrierType", LoadCarrierType.Bin2, typeof(Bin2Data))]
        [Subtype("CarrierType", LoadCarrierType.Palette, typeof(PalData))]
        [Subtype("CarrierType", LoadCarrierType.Pipe, typeof(PipeData))]
        public BaseCarrierData Data { get;  private set; }

        #endregion
    }
```

**Comment by jefffhaynes** [comment]
The source field will be determined from the target binding, not the other way around. You need to set the value of BaseCarrierData to something. Right now it's null, which isn't a valid option in your subtype bindings. 






On Fri, Jan 29, 2016 at 8:09 AM -0800, "Anhaltiner0708" <notifications@github.com> wrote:












From the serialization of the following object no bytes are written to the stream What is wrong?



Object that should serialized

new LoadCarrierData(LoadCarrierTypeUnknown, null);



I expect that two bytes (0x00, 0x00) are written to the stream! 

 public enum LoadCarrierType
    {
        /// <summary>
        /// unknown
        /// </summary>
        Unknown = 0, 

        /// <summary>
        /// bin 1
        /// </summary>
        Bin1 = 1, 

        /// <summary>
        /// bin 2
        /// </summary>
        Bin2 = 2, 

        /// <summary>
        /// palette
        /// </summary>
        Palette = 3, 

        /// <summary>
        /// pipe
        /// </summary>
        Pipe = 4
    }

public class LoadCarrierData
    {

        #region constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="LoadCarrierData"/> class
        /// </summary>
        public LoadCarrierData()
            : this(LoadCarrierTypeUnknown, null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoadCarrierData"/> class
        /// </summary>
        /// <param name="carrierType">
        /// The carrier Type
        /// </param>
        /// <param name="data">
        /// The data
        /// </param>
        public LoadCarrierData(LoadCarrierType carrierType, BaseCarrierData data)
            : base()
        {
            thisCarrierType = carrierType;
            thisData = data;
        }

        #endregion

        #region public properties  

        /// <summary>
        /// Gets or sets type of the load carrier
        /// </summary>
        [FieldOrder(0)]
        [SerializeAs(SerializedType = SerializedTypeUInt2)]
        public LoadCarrierType CarrierType { get; private set; }

        /// <summary>
        /// Gets or Sets the data
        /// </summary>
        [FieldOrder(1)]
        [Subtype("CarrierType", LoadCarrierTypeUnknown, typeof(BaseCarrierData))]
        [Subtype("CarrierType", LoadCarrierTypeBin1, typeof(Bin1Data))]
        [Subtype("CarrierType", LoadCarrierTypeBin2, typeof(Bin2Data))]
        [Subtype("CarrierType", LoadCarrierTypePalette, typeof(PalData))]
        [Subtype("CarrierType", LoadCarrierTypePipe, typeof(PipeData))]
        public BaseCarrierData Data { get;  private set; }

        #endregion
    }

**Comment by Anhaltiner0708** [comment]
You are right! But I think, in this case you can use the current value of the field "LoadCarrier". 

Ok, I will add some logic to avoid null in the "Data"-Field.

Many Thanks

**Comment by jefffhaynes** [comment]
Yes, I'm not sure why the default isn't used.  I'll look into that.

**Comment by jefffhaynes** [comment]
Thinking about it more, I think using the default would be dangerous as you could easily fall into a situation where the intent of the serialization contract is not being followed.  For example, the serializer may bind the default value to something valid (i.e. not Unknown) and in this case the deserializer would behave incorrectly.  Thinking about it, I can't think of good expected behavior for this sort of undefined case, so as of 4.6.2 I'm simply throwing an exception for null target bindings.  If I can come up with something better down the road such as a way to define default behavior that isn't too cumbersome, I can revisit.
