### ISSUE TITLE
OutOfMemoryException when deserializing array of int

### ISSUE THREAD

**Issue by xplicit** [jefffhaynes/BinarySerializer#3]
This code throws OutOfMemoryException. I use version 2.6.0 from nuget package.

	public class IntArray64K
	{
		[FieldLength(65536*sizeof(int))]
		public int[] Arr { get; set; }
	}

	class MainClass
	{
		public static void Main (string[] args)
		{
			BinarySerializer ser = new BinarySerializer ();
			byte[] data = new byte[65536 * sizeof(int)];

			IntArray64K des0=ser.Deserialize<IntArray64K>(data);

			using (MemoryStream ms = new MemoryStream (data)) {
				IntArray64K des=ser.Deserialize<IntArray64K>(ms);
			}

		}
	}

**Comment by jefffhaynes** [comment]
Ok, I'll take a look, thanks.

**Comment by xplicit** [comment]
I forgot to add environment. 

Mono JIT compiler version 3.10.0 (tarball Wed Nov  5 13:32:50 UTC 2014)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
OS: Ubuntu linux 32 bit

**Comment by jefffhaynes** [comment]
Yes, I was able to reproduce.  I'm going to push 3.0-beta pretty soon and
maybe you can take a look at that (it handles this correctly).

Thanks,

Jeff

On Fri, Jan 2, 2015 at 12:28 PM, Sergey Zhukov <notifications@github.com>
wrote:

> I forgot to add environment.
>
> Mono JIT compiler version 3.10.0 (tarball Wed Nov 5 13:32:50 UTC 2014)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors.
> www.mono-project.com
> TLS: __thread
> SIGSEGV: altstack
> Notifications: epoll
> Architecture: x86
> Disabled: none
> Misc: softdebug
> LLVM: supported, not enabled.
> GC: sgen
> OS: Ubuntu linux 32 bit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/BinarySerializer/issues/3#issuecomment-68544452>
> .
>



-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery

**Comment by xplicit** [comment]
Thank you,

waiting for new version :)

**Comment by jefffhaynes** [comment]
There is an alpha version on nuget if you want to try it.

**Comment by xplicit** [comment]
It works now, but serialization/deserialization takes to long (1.5 sec for one desirializing of the array). For comparison, version 2.6.0 serialized the array of ints for 0.09 sec per serialization.

**Comment by jefffhaynes** [comment]
I'll take a look but the biggest difference in 3.0 is that, similar to other serializers, it does most of the reflection up-front one time to increase the performance of subsequent serialization operations. Are you able to persist the serializer between operations and does that help?

Thanks

**Comment by xplicit** [comment]
This is the code, I use,  the seriazlier object is created only once.

			BinarySerializer ser = new BinarySerializer ();
			var arr = new IntArray64K(){Arr = DataFiller.FillIntArray (65536)};
			byte[] data;

			using (MemoryStream ms = new MemoryStream ()) {
				ser.Serialize (ms, arr);
				data = ms.ToArray ();
			}

			var b = Benchmark.StartNew ();

			for (int i = 0; i < 1000; i++) {
				using (MemoryStream ms = new MemoryStream (data)) {
					IntArray64K des=ser.Deserialize<IntArray64K>(ms);
				}
			}

			b.Stop ();

**Comment by jefffhaynes** [comment]
Ok, I see why.  I was thinking you had an array of bytes, which is a
special case.  The current implementation doesn't handle arrays of other
primitives very well.  I'll take a look and see if I can improve that.

On Sat, Jan 3, 2015 at 9:59 AM, Sergey Zhukov <notifications@github.com>
wrote:

> This is the code, I use, the seriazlier object is created only once.
>
>         BinarySerializer ser = new BinarySerializer ();
>         var arr = new IntArray64K(){Arr = DataFiller.FillIntArray (65536)};
>         byte[] data;
>
>         using (MemoryStream ms = new MemoryStream ()) {
>             ser.Serialize (ms, arr);
>             data = ms.ToArray ();
>         }
>
>         var b = Benchmark.StartNew ();
>
>         for (int i = 0; i < 1000; i++) {
>             using (MemoryStream ms = new MemoryStream (data)) {
>                 IntArray64K des=ser.Deserialize<IntArray64K>(ms);
>             }
>         }
>
>         b.Stop ();
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/BinarySerializer/issues/3#issuecomment-68597392>
> .
>



-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery

**Comment by xplicit** [comment]
You're right array of ints is significally slower than array of bytes on all serializers which I tried. But the issue that in version 2.6.0 array of ints was much faster than in version 3.0.0, while array of bytes became faster in version 3.0.0. Look at the benchmarks, I've did. Mean - is the mean time in milliseconds for 10K bytes array iteration and 1K ints iteration. Source code of the benchmarks you can find at https://github.com/xplicit/SerializersBenchmarks

Version 2.6.0

            name="DeserializeBytesStream"  mean="1329.21988"
            name="SerializeBytesStream" mean="2478.95462"
            name="SerializeIntsStream" mean="81136.5969"

Version 3.0.0

            name="DeserializeBytesStream" mean="944.65618"
            name="SerializeBytesStream" mean="1812.23482"
            name="SerializeIntsStream" mean="1706002.52326"
            name="DeserializeIntsStream" mean="1585196.82124"

Serialization of ints became 20 times slower in new version.

**Comment by jefffhaynes** [comment]
Yes, it has to do with the reflection stage in 3.0. I can fix it :)

**Comment by jefffhaynes** [comment]
Ok, please try the latest alpha.  It should be much faster.  Also, note
that you can rewrite your array class declaration like this and accomplish
the same thing:

    public class IntArray64K
    {
        [FieldCount(65536)]
        public int[] Array { get; set; }
    }

Thanks, I'd be interested to see your test results with this change.

Regards,

Jeff


On Sat, Jan 3, 2015 at 1:09 PM, Jeff Haynes <feedyurhed@gmail.com> wrote:

> Yes, it has to do with the reflection stage in 3.0. I can fix it :)
>
>
> On Jan 3, 2015, at 12:59 PM, Sergey Zhukov <notifications@github.com>
> wrote:
>
> You're right array of ints is significally slower than array of bytes on
> all serializers which I tried. But the issue that in version 2.6.0 array of
> ints was much faster than in version 3.0.0, while array of bytes became
> faster in version 3.0.0. Look at the benchmarks, I've did. Mean - is the
> mean time in milliseconds for 10K bytes array iteration and 1K ints
> iteration. Source code of the benchmarks you can find at
> https://github.com/xplicit/SerializersBenchmarks
>
> Version 2.6.0
>
>         name="DeserializeBytesStream"  mean="1329.21988"
>         name="SerializeBytesStream" mean="2478.95462"
>         name="SerializeIntsStream" mean="81136.5969"
>
> Version 3.0.0
>
>         name="DeserializeBytesStream" mean="944.65618"
>         name="SerializeBytesStream" mean="1812.23482"
>         name="SerializeIntsStream" mean="1706002.52326"
>         name="DeserializeIntsStream" mean="1585196.82124"
>
> Serialization of ints became 20 times slower in new version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/BinarySerializer/issues/3#issuecomment-68603402>
> .
>
>


-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery

**Comment by xplicit** [comment]
Thank you!

Now it's working as expected.

**Comment by xplicit** [comment]
Here are benchmarks (Please note, that for ints I use only 100 iterations now instead of 1000 last time)

      DeserializeBytesArray => ****** Mean=935.17, Min=899.18, Max=969.97, StdDev=29.88, StdErr=1.43%
      DeserializeBytesStream => ****** Mean=927.97, Min=897.41, Max=1034.87, StdDev=53.52, StdErr=2.58%
      DeserializeIntsStream => ****** Mean=2427.14, Min=2401.53, Max=2474.82, StdDev=27.32, StdErr=0.50%
      SerializeBytesStream => ****** Mean=1810.47, Min=1743.48, Max=1873.75, StdDev=44.88, StdErr=1.11%
      SerializeIntsStream => ****** Mean=2062.52, Min=2059.11, Max=2063.97, StdDev=1.74, StdErr=0.04%

**Comment by xplicit** [comment]
So it looks 4x faster than 2.6.0

**Comment by jefffhaynes** [comment]
Great, I'm going to keep looking for optimizations. I think I should be able to get some more out of it. Thanks!

**Comment by jefffhaynes** [comment]
Hey, I put up some documentation.  Take a look when you get a chance.

https://github.com/jefffhaynes/BinarySerializer/tree/generated

On Sat, Jan 3, 2015 at 10:28 PM, Jeff Haynes <feedyurhed@gmail.com> wrote:

> Great, I'm going to keep looking for optimizations. I think I should be
> able to get some more out of it. Thanks!
>
>
> On Jan 3, 2015, at 8:53 PM, Sergey Zhukov <notifications@github.com>
> wrote:
>
> So it looks 4x faster than 2.6.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/BinarySerializer/issues/3#issuecomment-68617441>
> .
>
>


-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery
