### ISSUE TITLE
TargetParameterCountException while deserialization

### ISSUE THREAD

**Issue by alexander9999** [jefffhaynes/BinarySerializer#30]
in my app the BinarySerializer is used for Serialization of Tcp/Ip communication, one TargetParameterCountException is thrown while calling Deserialize method. i have prepared a simple Project for test it, there is 3 constructors in Header.cs, if the both constructors with Parameters are commented out, no exceptions occur, otherwise, one TargetParameterCountException is from code line
value = subType.Constructor.Invoke(parameterValues) in class ObjectValueNode thrown.

i can't attach source code per zip, so i wrote it in one txt file, which has 7 simple .cs files, please have Patience!
Thanks

[Classes4test.txt](https://github.com/jefffhaynes/BinarySerializer/files/117904/Classes4test.txt)

**Comment by jefffhaynes** [comment]
Ok, I'll take a look as soon as I can. Thanks.

**Comment by jefffhaynes** [comment]
This is fixed in 4.6.1.  Let me know if you have any other issues with it.

Thanks

**Comment by jefffhaynes** [comment]
Also note, that while there was an issue with constructor matching, you also may not be getting the results you expect as some of the parameter names are close but not exact matches of field names.  For example, the sender parameter will not match the senderId field.  The names must be case-insensitive matches.

**Comment by alexander9999** [comment]
yes, you are right, the Version 4.6.0 was used, now that it is OK!

Thanks
