### ISSUE TITLE
Null-terminated string will not fully deserialized 

### ISSUE THREAD

**Issue by Anhaltiner0708** [jefffhaynes/BinarySerializer#33]
Serialization of following is running fine! But the deserialization is going wrong! It seems, that the deserialisation of the string property is finished after the first 0 byte. What can I do to solve this problem?

Deserialisation of following bytes

```C# 
0xFE, 0x31, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02
```

Returns following object

```C# 
Bin3Data() { BinType = 254, Ident = "1", Occupancy = BinOccupancy.Unknown }
```

But expected is

```C# 
Bin3Data() { BinType = 254, Ident = "1", Occupancy = BinOccupancy.Full }
```

example class
```c#
   public enum BinOccupancy
	{
		/// <summary>
		/// The unknown.
		/// </summary>
		Unknown = 0, 

		/// <summary>
		/// The empty.
		/// </summary>
		Empty = 1, 

		/// <summary>
		/// The full.
		/// </summary>
		Full = 2, 
	}

    public class Bin3Data
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="Bin3Data"/> class.
		/// </summary>
		public Bin3Data()
			: base()
		{
		}

		/// <summary>
		/// Gets or sets type of the bin
		/// </summary>
		[FieldOrder(0)]
		[SerializeAs(SerializedType = SerializedType.UInt1)]
		public byte BinType { get; set; }

		/// <summary>
		/// Gets or sets ident
		/// </summary>
		[FieldOrder(1)]
		[FieldLength(31)] 
		[SerializeAs(SerializedType = SerializedType.NullTerminatedString)]
		public string Ident { get; set; }

		/// <summary>
		/// Gets or sets Occupancy
		/// </summary>
		[FieldOrder(2)]
		[SerializeAs(SerializedType = SerializedType.UInt1)]
		public BinOccupancy Occupancy { get; set; }
	}
```

test methode
```C#
		[Test]
		public void DeserializeMessage()
		{
			var serializer = new BinarySerializer() { Endianness = Endianness.Little };
			var inBytes = new byte[]
				              {
					              0xFE, 0x31, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
					              0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02
				              };
			var expectedObj = new Bin3Data() { BinType = 254, Ident = "1", Occupancy = BinOccupancy.Full };

			Bin3Data actualObj;
			using (var stream = new MemoryStream(inBytes))
			{
				actualObj = serializer.Deserialize<Bin3Data>(stream);
			}

			if (!expectedObj.Equals(actualObj))
			{
				Assert.Fail(
					string.Format(
						CultureInfo.InvariantCulture,
						"Objects are not equal. Expected: {0} Result: {1}",
						expectedObj.ToString(),
						actualObj.ToString()));
			}
		}
```

**Comment by jefffhaynes** [comment]
Yup, appears to be a bug.  If you want, for the time being you can remove [SerializeAs(SerializedType = SerializedType.NullTerminatedString)] since that isn't really doing anything (other than confusing the serializer).  It should realize that even though it's null terminated, it needs to read the entire 31 bytes.

Thanks

**Comment by jefffhaynes** [comment]
Pushed in 4.6.5.  Cheers.

**Comment by Anhaltiner0708** [comment]
I have tried the new Version. But it ignores the first occurrence of 0 byte, if the byte stream is a bit dirty.

I use the following source bytes. You can see there bytes that have a value other than 0, and stand behind the first 0 byte. After I have derserialized this, I get a string with the character '\0'. ("1\03")

```C#
 0xFE, 0x31, 0x00, 0x33, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02
```

**Comment by Anhaltiner0708** [comment]
I have added the property 'OccupancyString' to my sample class. (see below). This property is an enum and is serialized as null terminating string. In version 4.6.4 it works fine. But in the latest version  is thrown an exception

>  'System.InvalidOperationException : Unable to write beyond end of stream limit'

> StackTrace:	
bei BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(LimitedStream stream, EventShuttle eventShuttle)
   bei BinarySerialization.BinarySerializer.Serialize(Stream stream, Object value, Object context)
   bei Communication.External.Plc.Messages.Nunit.Order.MsgOrderStateTests.SerializeMessage() in E:\Projects\L2Future\Internal\Code\PLCMessage\Nunit\PlcControllerMessageLib\Order\MsgOrderStateTests.cs:Zeile 85.
--InvalidOperationException
   bei BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(LimitedStream stream, EventShuttle eventShuttle)
   bei BinarySerialization.Graph.ValueGraph.ContextValueNode.SerializeOverride(LimitedStream stream, EventShuttle eventShuttle)
   bei BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(LimitedStream stream, EventShuttle eventShuttle)
--InvalidOperationException
   bei BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(LimitedStream stream, EventShuttle eventShuttle)
   bei BinarySerialization.Graph.ValueGraph.ObjectValueNode.ObjectSerializeOverride(LimitedStream stream, EventShuttle eventShuttle)
   bei BinarySerialization.Graph.ValueGraph.ObjectValueNode.SerializeOverride(LimitedStream stream, EventShuttle eventShuttle)
   bei BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(LimitedStream stream, EventShuttle eventShuttle)
--InvalidOperationException
   bei BinarySerialization.LimitedStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   bei System.IO.BinaryWriter.Write(Byte[] buffer)
   bei BinarySerialization.Graph.ValueGraph.ValueValueNode.Serialize(EndianAwareBinaryWriter writer, Object value, SerializedType serializedType, Nullable`1 length)
   bei BinarySerialization.Graph.ValueGraph.ValueValueNode.Serialize(Stream stream, Object value, SerializedType serializedType, Nullable`1 length)
   bei BinarySerialization.Graph.ValueGraph.EnumValueNode.SerializeOverride(LimitedStream stream, EventShuttle eventShuttle)
   bei BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(LimitedStream stream, EventShuttle eventShuttle)
Ergebnis Meldung:	
System.InvalidOperationException : Error serializing type 'Communication.External.Plc.Messages.Nunit.Order.Bin3Data'.  See inner exception for detail.
  ----> System.InvalidOperationException : Error serializing type 'Communication.External.Plc.Messages.Nunit.Order.Bin3Data'.  See inner exception for detail.
  ----> System.InvalidOperationException : Error serializing member 'OccupancyString'.  See inner exception for detail.
  ----> System.InvalidOperationException : Unable to write beyond end of stream limit.

```c#
public class Bin3Data
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="Bin3Data"/> class.
		/// </summary>
		public Bin3Data()
			: base()
		{
		}

		/// <summary>
		/// Gets or sets type of the bin
		/// </summary>
		[FieldOrder(0)]
		[SerializeAs(SerializedType = SerializedType.UInt1)]
		public byte BinType { get; set; }

		/// <summary>
		/// Gets or sets ident
		/// </summary>
		[FieldOrder(1)]
		[FieldLength(31)]
		[SerializeAs(SerializedType = SerializedType.NullTerminatedString)]
		public string Ident { get; set; }

		/// <summary>
		/// Gets or sets Occupancy
		/// </summary>
		[FieldOrder(2)]
		[SerializeAs(SerializedType = SerializedType.UInt1)]
		public BinOccupancy Occupancy { get; set; }


		/// <summary>
		/// Gets or sets Occupancy
		/// </summary>
		[FieldOrder(3)]
		[FieldLength(6)]
		[SerializeAs(SerializedType = SerializedType.NullTerminatedString)]
		public BinOccupancy OccupancyString { get; set; }
	}
```

test method
```c#
		[Test]
		public void SerializeMessage()
		{
			var serializer = new BinarySerializer() { Endianness = Endianness.Little };
			var expectedBytes = new byte[]
				                    {
					                    0xFE, 0x31, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
					                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
					                    0x02, Convert.ToByte('E'), Convert.ToByte('m'), Convert.ToByte('p'), Convert.ToByte('t'),
					                    Convert.ToByte('y'), 0x00,
				                    };

			var inObj = new Bin3Data() { BinType = 254, Ident = "1", Occupancy = BinOccupancy.Full, OccupancyString = BinOccupancy.Empty}; 

			byte[] actualBytes;
			using (var stream = new MemoryStream())
			{
				serializer.Serialize(stream,inObj);
				actualBytes = stream.ToArray();
			}

			Assert.AreEqual(expectedBytes,actualBytes, "Objects are not equal");
		}
```

**Comment by jefffhaynes** [comment]
I think I understand the problem. Let me work on it. 






On Tue, Apr 12, 2016 at 4:41 AM -0700, "Anhaltiner0708" <notifications@github.com> wrote:












I have added the property 'OccupancyString' to my sample class. (see below). This property is an enum and is serialized as null terminating string. In version 4.6.4 it works fine. But in the latest version  is thrown an exception




'System.InvalidOperationException : Unable to write beyond end of stream limit'



StackTrace:


bei BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(LimitedStream stream, EventShuttle eventShuttle)

   bei BinarySerialization.BinarySerializer.Serialize(Stream stream, Object value, Object context)

   bei Communication.External.Plc.Messages.Nunit.Order.MsgOrderStateTests.SerializeMessage() in E:\Projects\L2Future\Internal\Code\PLCMessage\Nunit\PlcControllerMessageLib\Order\MsgOrderStateTests.cs:Zeile 85.

--InvalidOperationException

   bei BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(LimitedStream stream, EventShuttle eventShuttle)

   bei BinarySerialization.Graph.ValueGraph.ContextValueNode.SerializeOverride(LimitedStream stream, EventShuttle eventShuttle)

   bei BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(LimitedStream stream, EventShuttle eventShuttle)

--InvalidOperationException

   bei BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(LimitedStream stream, EventShuttle eventShuttle)

   bei BinarySerialization.Graph.ValueGraph.ObjectValueNode.ObjectSerializeOverride(LimitedStream stream, EventShuttle eventShuttle)

   bei BinarySerialization.Graph.ValueGraph.ObjectValueNode.SerializeOverride(LimitedStream stream, EventShuttle eventShuttle)

   bei BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(LimitedStream stream, EventShuttle eventShuttle)

--InvalidOperationException

   bei BinarySerialization.LimitedStream.Write(Byte[] buffer, Int32 offset, Int32 count)

   bei System.IO.BinaryWriter.Write(Byte[] buffer)

   bei BinarySerialization.Graph.ValueGraph.ValueValueNode.Serialize(EndianAwareBinaryWriter writer, Object value, SerializedType serializedType, Nullable1 length)

   bei BinarySerialization.Graph.ValueGraph.ValueValueNode.Serialize(Stream stream, Object value, SerializedType serializedType, Nullable1 length)

   bei BinarySerialization.Graph.ValueGraph.EnumValueNode.SerializeOverride(LimitedStream stream, EventShuttle eventShuttle)

   bei BinarySerialization.Graph.ValueGraph.ValueNode.Serialize(LimitedStream stream, EventShuttle eventShuttle)

Ergebnis Meldung:


System.InvalidOperationException : Error serializing type 'Communication.External.Plc.Messages.Nunit.Order.Bin3Data'.  See inner exception for detail.

  ----> System.InvalidOperationException : Error serializing type 'Communication.External.Plc.Messages.Nunit.Order.Bin3Data'.  See inner exception for detail.

  ----> System.InvalidOperationException : Error serializing member 'OccupancyString'.  See inner exception for detail.

  ----> System.InvalidOperationException : Unable to write beyond end of stream limit.


public class Bin3Data
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Bin3Data"/> class.
        /// </summary>
        public Bin3Data()
            : base()
        {
        }

        /// <summary>
        /// Gets or sets type of the bin
        /// </summary>
        [FieldOrder(0)]
        [SerializeAs(SerializedType = SerializedType.UInt1)]
        public byte BinType { get; set; }

        /// <summary>
        /// Gets or sets ident
        /// </summary>
        [FieldOrder(1)]
        [FieldLength(31)]
        [SerializeAs(SerializedType = SerializedType.NullTerminatedString)]
        public string Ident { get; set; }

        /// <summary>
        /// Gets or sets Occupancy
        /// </summary>
        [FieldOrder(2)]
        [SerializeAs(SerializedType = SerializedType.UInt1)]
        public BinOccupancy Occupancy { get; set; }


        /// <summary>
        /// Gets or sets Occupancy
        /// </summary>
        [FieldOrder(3)]
        [FieldLength(6)]
        [SerializeAs(SerializedType = SerializedType.NullTerminatedString)]
        public BinOccupancy OccupancyString { get; set; }
    }



test method

        [Test]
        public void SerializeMessage()
        {
            var serializer = new BinarySerializer() { Endianness = Endianness.Little };
            var expectedBytes = new byte[]
                                    {
                                        0xFE, 0x31, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                        0x02, Convert.ToByte('E'), Convert.ToByte('m'), Convert.ToByte('p'), Convert.ToByte('t'),
                                        Convert.ToByte('y'), 0x00,
                                    };

            var inObj = new Bin3Data() { BinType = 254, Ident = "1", Occupancy = BinOccupancy.Full, OccupancyString = BinOccupancy.Empty}; 

            byte[] actualBytes;
            using (var stream = new MemoryStream())
            {
                serializer.Serialize(stream,inObj);
                actualBytes = stream.ToArray();
            }

            Assert.AreEqual(expectedBytes,actualBytes, "Objects are not equal");
        }

**Comment by jefffhaynes** [comment]
Ok, 4.7 should fix both of these issues.  The real problem was that in certain cases the serializer was glossing over the handling of null-terminated strings and it's more explicit now.

**Comment by Anhaltiner0708** [comment]
Thank you so much! It works well. You're doing a great job.

**Comment by jefffhaynes** [comment]
No worries, thanks!






On Tue, Apr 12, 2016 at 9:46 PM -0700, "Anhaltiner0708" <notifications@github.com> wrote:












Thank you so much! It works well. You're doing a great job.
