### ISSUE TITLE
serialization of S7-String

### ISSUE THREAD

**Issue by Anhaltiner0708** [jefffhaynes/BinarySerializer#34]
Hi Jeff,

I like to create an class, that contains the properties of a S7-String.

- MaxLength
- CurrentLength
- Value (String)

![s7-string](https://cloud.githubusercontent.com/assets/16814073/14664726/c716f822-06cd-11e6-8fc0-c19989091ab7.gif)

Serialization should return a stream of length Maxlength + 2 (bytes of max and current length).I would not use constants and bind the MaxLength property to the FieldLengthAttribute of the property Value. However, this leads to the result that the length of the stream depends on the property value and not on the property MaxLength.

Is there a way to define it without using the interface IBinarySerializable?

Best regards
Dirk

**Comment by jefffhaynes** [comment]
If I'm understanding it correctly can you define a S7 string class that contains a string and bind the class size separately?  I apologize as I'm not in front of a computer but would something like this achieve the desired effect?
public class S7StringInternal{    [FieldOrder(0)]    public int Length;
    [FieldOrder(1)]    [FieldLength("Length")]    public string Value;}
public class S7String{    [FieldOrder(0)]    public int MaxLength;
    [FieldOrder(1)]    [FieldLength("MaxLength")]    public S7StringInternal Value;}

Although as I'm writing this I realize this wouldn't work for serialization as the MaxLength value has to come from somewhere. You might be able to specify the binding direction and make that work, I'm not sure. When I get a chance I'll try it out and see but see if you have any luck with this. 



On Tue, Apr 19, 2016 at 11:26 PM -0700, "Anhaltiner0708" <notifications@github.com> wrote:












Hi Jeff,



I like to create an class, that contains the properties of a S7-String.


MaxLength
CurrentLength
Value (String)








Serialization should return a stream of length Maxlength + 2 (bytes of max and current length).I would not use constants and bind the MaxLength property to the FieldLengthAttribute of the property Value. However, this leads to the result that the length of the stream depends on the property value and not on the property MaxLength.



Is there a way to define it without using the interface IBinarySerializable?



Best regards

Dirk

**Comment by Anhaltiner0708** [comment]
Thank you for your quick response. I tried your suggestion and think it goes in the right direction.

I have defined the following classes. The result of the serilisation has one byte lesser than expected. The deserilisation of this class seems to work fine.

```C#
public object Convert(object value, object parameter, BinarySerializationContext context)
    {
        if (!(value is byte) || !(parameter is byte))
        {
            return (byte)0;
        }


        return (byte)value + (byte)parameter;
    }

    public object ConvertBack(object value, object parameter, BinarySerializationContext context)
    {
        if (!(value is byte) || !(parameter is byte))
        {
            return (byte)0;
        }


        return (byte)value - (byte)parameter;
    }
}

public class InternalS7String
{
    public InternalS7String()
    {
    }

    public InternalS7String(byte length, string value)
    {
        this.Value = value;
    }

    private string value;

    [FieldOrder(0)]
    public byte Length
    {
        get
        {
            return (string.IsNullOrEmpty(this.Value)
                        ? (byte)0
                        : Convert.ToByte(this.Value.Length));
        }
    }

    [FieldOrder(1)]
    [FieldLength("Length", BindingMode=BindingMode.OneWay)]
    public string Value
    {
        get
        {
            return this.value;
        }
        set
        {
            if (value == null)
            {
                this.value = string.Empty;
                return;
            }

            this.value = value;
        }
    }
}

public class S7String
{
    public S7String()
    {
        this.Value = new InternalS7String();
    }
        

    [FieldOrder(0)]
    public byte MaxLength { get; set; }

    [FieldOrder(1)]
    [FieldLength("MaxLength", ConverterType = typeof(IncreaseValueConverter), ConverterParameter = (byte) 1, BindingMode = BindingMode.OneWay)]
    public InternalS7String Value { get; set; }
}
```

**Comment by jefffhaynes** [comment]
I just tried this:

```c#
   class AdditionConverter : IValueConverter
    {
        public object Convert(object value, object parameter, BinarySerializationContext context)
        {
            return (System.Convert.ToInt32(value) + System.Convert.ToInt32(parameter));
        }

        public object ConvertBack(object value, object parameter, BinarySerializationContext context)
        {
            return (System.Convert.ToInt32(value) - System.Convert.ToInt32(parameter));
        }
    }

 public class InternalS7String
    {
        public InternalS7String()
        {
        }

        public InternalS7String(string value)
        {
            Value = value;
        }

        [FieldOrder(0)]
        public byte Length { get; set; }

        [FieldOrder(1)]
        [FieldLength("Length")]
        public string Value { get; set; }
    }

    public class S7String
    {
        [FieldOrder(0)]
        public byte MaxLength { get; set; }

        [FieldOrder(1)]
        [FieldLength("MaxLength", ConverterType = typeof(AdditionConverter), ConverterParameter = 1)]
        public InternalS7String Value { get; set; }
    }
```

and it seemed to work but it's possible I'm missing something.  I'm also not sure that it's a very elegant solution.  It may be that to truly support something like this the framework would need to have max/min parameters or something.

One thing to note in your example is that computed properties are not supported by the serializer.  The first thing it does is analyze the object graph and build an internal representation.  Building the graph makes for very fast serialization but unfortunately loses anything other than the field name, type, bindings, etc. in the process.

**Comment by jefffhaynes** [comment]
I realized you can also eliminate the converter by having both length fields outside the internal object. Did you ever get this working?

**Comment by Anhaltiner0708** [comment]
Hi Jeff,

I found following solution. This works fine in both directions.

Thanks

```C#


    public class S7String
    {

	public S7String()
	{
	}

	public S7String(byte maxLength, byte actualLength, string fixedSizeValue)
	{
		this.MaxLength = maxLength;
		this.Value = (actualLength==0) ? string.Empty : fixedSizeValue.Substring(0,actualLength);
	}

        [FieldOrder(0)]
        public byte MaxLength { get; set; }
	
	[FieldOrder(1)]
	public byte ActualLength
		=>
			string.IsNullOrEmpty(this.Value)
				? (byte)0
				: (this.Value.Length >= this.MaxLength) 
                                      ? this.MaxLength 
                                       : Convert.ToByte(this.Value.Length);
	[FieldOrder(2)]
	[FieldLength("MaxLength")]
	[SerializeAs(SerializedType.SizedString)]
	public string FixedSizeValue
	{
		get
		{
			return this.Value.PadRight(this.MaxLength, '\0');
		}
	}

        [Ignore]
        public string Value { get; set; }
    }

```
