### ISSUE TITLE
Checksum support

### ISSUE THREAD

**Issue by hs3180** [jefffhaynes/BinarySerializer#36]
It will be very nice if `BinarySerializer` supports checksum or custom function.

    [FieldOrder(0)]
    public byte FieldA { get; set; }
    [FieldOrder(1)]
    public byte FieldB { get; set; }
    [FieldOrder(2)]
    public byte FieldC { get; set; }
    [FieldOrder(3)]
    [Checksum]   // or [CustomFunc(myFunc)]
    public byte Checksum { get; }

It may be similar to `[FieldLength("Length")]`, which `Length` could be generated and overwriten in serializing progress.

**Comment by jefffhaynes** [comment]
I agree. In fact, I was just thinking about this again yesterday. Unfortunately it's a little tricky as the checksum doesn't exist at the data level but really at the protocol level. That is to say, you have to first serialize the data and then calculate the checksum, which can lead to some complex dependencies. But let me work on it...
Thanks for the feedback!






On Wed, Apr 27, 2016 at 11:54 PM -0700, "Shan Huang" <notifications@github.com> wrote:












It will be very nice if BinarySerializer supports checksum or custom function.

[FieldOrder(0)]
public byte FieldA { get; set; }
[FieldOrder(1)]
public byte FieldB { get; set; }
[FieldOrder(2)]
public byte FieldC { get; set; }
[FieldOrder(3)]
[Checksum]   // or [CustomFunc(myFunc)]
public byte Checksum { get; }




It may be similar to [FieldLength("Length")], which Length could be generated and overwriten in serializing progress.

**Comment by jefffhaynes** [comment]
I have an initial check-in of CRC support in the checksum branch if you want to play with it

**Comment by jefffhaynes** [comment]
Thanks for the prod in the right direction.  I just pushed 5.0, which includes CRC support.  Please let me know if you have any issues with it.
