### ISSUE TITLE
Access FieldLength attribute value from IBinarySerializable class?

### ISSUE THREAD

**Issue by rkirkpat** [jefffhaynes/BinarySerializer#37]
To interface with some legacy hardware a couple custom (de)serializers are needed for special data types that have variable but predefined lengths (i.e. length not defined in the data but by protocol specs). I have a working IBinarySerializable class but need to know how many bytes there are to generate or parse for a specific instance of the class. It appears that LimitedStream has the information I want in MaxLength, but as it is an internal class to BinarySerializer, I can't access it. 

Is there a way, in an IBinarySerializable based class, to figure out how many bytes can be read or written (without wasting time probing, causing exceptions and catching them)? Thanks!

**Comment by jefffhaynes** [comment]
No, but it might make sense to expose that information.  I'll take a look
at it.

Cheers

On Mon, May 9, 2016 at 8:12 PM, rkirkpat <notifications@github.com> wrote:

> To interface with some legacy hardware a couple custom (de)serializers are
> needed for special data types that have variable but predefined lengths
> (i.e. length not defined in the data but by protocol specs). I have a
> working IBinarySerializable class but need to know how many bytes there are
> to generate or parse for a specific instance of the class. It appears that
> LimitedStream has the information I want in MaxLength, but as it is an
> internal class to BinarySerializer, I can't access it.
>
> Is there a way, in an IBinarySerializable based class, to figure out how
> many bytes can be read or written (without wasting time probing, causing
> exceptions and catching them)? Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jefffhaynes/BinarySerializer/issues/37>
>



-- 
If you want to build a ship, don't drum up people together to collect wood
and don't assign them tasks and work, but rather teach them to long for the
endless immensity of the sea.

Antoine de Saint-Exupery

**Comment by jefffhaynes** [comment]
This is available in 5.0.2.  I also changed the name to BoundedStream just because "limited" sounded like it didn't do much :).  Unfortunately I can't change the IBinarySerializable signature but you can now cast to BoundedStream and get the info you want.

**Comment by rkirkpat** [comment]
Excellent, that change should fit my need perfectly. Thanks!

**Comment by jefffhaynes** [comment]
Great glad to hear it. Cheers






On Wed, May 11, 2016 at 3:42 PM -0700, "rkirkpat" <notifications@github.com> wrote:












Excellent, that change should fit my need perfectly. Thanks!
