### ISSUE TITLE
InvalidOperationException when deserializing byte stream into bool array

### ISSUE THREAD

**Issue by Mephistofeles** [jefffhaynes/BinarySerializer#39]
I have a class as follows:

```
    public class InputsStateFrameData : FrameData
    {
        public InputsStateFrameData(bool[] inputs)
        {
            //Debug.Assert(inputs.Count == 16, "There should be 16 inputs.");
            Inputs = inputs;
        }

        [FieldCount(16)]
        public bool[] Inputs { get; }
    }
```

It's a part of a full message frame, and I can serialize whole frame using BinarySerializer without problems. When I try to deserialize serialized byte stream or prepared array of bytes:
```
0xFF,
0x13,
0,
1,
0,
1,
0,
1,
0,
1,
0,
1,
0,
1,
0,
1,
0,
1,
0xFE
```
I get InvalidOperationException with inner ArgumentException:

> Additional information: Cannot widen from source type to target type either because the source type is a not a primitive type or the conversion cannot be accomplished.

It is thrown by the Array.SetValue method in [SetCollectionValue method](https://github.com/jefffhaynes/BinarySerializer/blob/master/BinarySerializer/Graph/ValueGraph/PrimitveArrayValueNode.cs#L57) from PrimitveArrayValueNode
```
        protected override void SetCollectionValue(object item, int index)
        {
            var array = (Array)BoundValue;
            array.SetValue(item, index);
        }
```
When I tried replacing array by List<bool> it doesn't work anyway, just the exceptions are different:

> The value "0" is not of type "System.Boolean" and cannot be used in this generic collection

This method tries to set boolean value with byte without any conversion, so it throws exceptions like that.

I am wondering why this part:
```
            var items =
                DeserializeCollection(stream, eventShuttle).ToList();

            var itemCount = items.Count;

            /* Create final collection */
            Value = CreateCollection(itemCount);

            /* Copy temp list into final collection */
            for (var i = 0; i < itemCount; i++)
                SetCollectionValue(items[i], i);
```
Is implemented that way, iterating with SetCollectionValue instead of just using CreateCollection with items enumerable, which uses TypeConverters.ConvertTo method to convert deserialized value into the collection child type.

**Comment by jefffhaynes** [comment]
Yup, definitely an issue.  Unfortunately I can't use the CreateCollection override because it won't deal with arrays of arrays and probably some other corner cases.  However, I was missing the converter call in both SetCollectionValue overrides so I fixed that.  Also found another bug while I was in this area of the code so definitely a good catch, thanks!

Fixed in 5.0.3.
