### ISSUE TITLE
[FieldCount] does not work on byte arrays

### ISSUE THREAD

**Issue by xplicit** [jefffhaynes/BinarySerializer#4]
When trying to deserialize byte array object with FieldCount attribute , an exception occures:  System.InvalidOperationException : No length specified on byte array.

The object

        public class ByteArray64K
        {
	        [FieldCount(65536)]
	        public byte[] Arr { get; set; }
        }

**Comment by jefffhaynes** [comment]
Is this against the 3.0.0-rc?  I think this was fixed in that...

**Comment by xplicit** [comment]
I didn't see that -rc package is available on nuget. It's fixed it it.
