### ISSUE TITLE
Set FieldLenght to the rest of the object

### ISSUE THREAD

**Issue by Aquariusquintini** [jefffhaynes/BinarySerializer#49]
Hi,

I'm new to BinarySerializer, but I would like to use it for my project. I have a usage scenario were I have the following format:

```
public class MessageBase{
   [FieldOrder(0)]
   public MessageHeader Header { get; set; }
   [FieldOrder(1)]
   public RemoteOperationHeader RemoteOpHeader { get; set; }
   [FieldOrder(2)]
   [Subtype("RemoteOpHeader.OpType", RemoteOpTypes.Invoke, typeof(RemoteInvokeOp))]
   [Subtype("RemoteOpHeader.OpType", RemoteOpTypes.Command, typeof(RemoteInvokeComm))]
   [Subtype("RemoteOpHeader.OpType", RemoteOpTypes.Result, typeof(RemoteInvokeRes))]
   public RemoteOperationBase RemoteOperation { get; set; }
}
```
```
public class MessageHeader
{
      [FieldOrder(0)]
       public MessageType MessageType {get;set;}

      [FieldOrder(1)]
       public int MessageLength {get;set;} // Should be the length of the remainder of the message, i.e. the number of bytes that will follow.
}

```
```
public class RemoteOperationHeader
{
      [FieldOrder(0)]
       public RemoteOpTypes OpType {get;set;}

      [FieldOrder(1)]
       public int Length {get;set;} // Should be the length of the remainder of the message, i.e. the number of bytes that will follow.
}
```
```
public class Message:MessageBase{
      // Should inherit the members of the base class and then add the next element to the message     
     [FieldOrder(0)]
     public RemoteInvokeAction Action{get;set;}
}
```

Is such a scenario supported? And if yes, how can it be achieved?

Kind regards.

**Comment by jefffhaynes** [comment]
I would consider refactoring the first part into something like this:

```c#
    public class MessageBase
    {
        [FieldOrder(0)]
        public MessageHeader Header { get; set; }

        [FieldOrder(1)]
        [FieldLength("Header.MessageLength")]
        public MessageContent Content { get; set; }
    }

    public class MessageContent
    {
        [FieldOrder(1)]
        public RemoteOperationHeader RemoteOpHeader { get; set; }

        [FieldOrder(2)]
        [FieldLength("RemoteOpHeader.Length")]
        [Subtype("RemoteOpHeader.OpType", RemoteOpTypes.Invoke, typeof(RemoteInvokeOp))]
        [Subtype("RemoteOpHeader.OpType", RemoteOpTypes.Command, typeof(RemoteInvokeComm))]
        [Subtype("RemoteOpHeader.OpType", RemoteOpTypes.Result, typeof(RemoteInvokeRes))]
        public RemoteOperationBase RemoteOperation { get; set; }
    }
```

However, I'm not sure I understand the last part or if the length values need to include the additional field.  If so, it might be complicated to set up the hierarchy correctly.

In general I try to break the format into many different objects and try to understand the intended design of the format.  Sometimes this results in very deep hierarchies but I don't think you should be afraid of that.  Depending on what you're trying to accomplish you also may need to rethink your object model, especially if the inheritance design does not align with the intended extensibility model of the format you're trying to match.

**Comment by jefffhaynes** [comment]
Any luck with this?

**Comment by jefffhaynes** [comment]
The length should be set correctly in the serialized output. However the original object will not be updated or changed. If you want to see what values are being set you can either hook up the serialized events or possibly deserialize the result. Also TwoWay is the default so you shouldn't have to set it. 






On Thu, Sep 29, 2016 at 2:30 AM -0400, "Aquariusquintini" <notifications@github.com> wrote:












Yes, works like a charm. I devided the message in a hierarchy like you suggested and everything is correctly serialized and deserialized.



Only question that remains: I tried a TwoWay binding to let the serializer set the value of the Length property, but that didn't work, the value of Length remained 0. Is it possible to set the values on serialization (to ensure that my object state also reflects the serialized values for length)?
