### ISSUE TITLE
Just left alignment

### ISSUE THREAD

**Issue by grandkarabas** [jefffhaynes/BinarySerializer#51]
Hi Jeff,

As I understand FieldAlignment attribute sets both left and right alignment. I did not find how to set just left alignment, not both (I need it to describe DCE RPC message). Is it possible now?

Thank you in advance.

**Comment by jefffhaynes** [comment]
It's not currently possible but I can look at adding it. Could you post an example of what you're trying to accomplish?

---------------
I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses - Johannes Kepler




On Wed, Dec 14, 2016 at 8:09 AM -0500, "grandkarabas" <notifications@github.com> wrote:












Hi Jeff,


As I understand FieldAlignment attribute sets both left and right alignment. I did not find how to set just left alignment, not both (I need it to describe DCE RPC message). Is it possible now?


Thank you in advance.

**Comment by grandkarabas** [comment]
Yes of course. I need for the first field (rpc_vers) to be 8-octet aligned at left, and for the next one (rpc_vers_minor) to start in the next byte.

`
typedef struct {

      /* start 8-octet aligned */

      /* common fields */
        u_int8  rpc_vers = 5;       /* 00:01 RPC version */
        u_int8  rpc_vers_minor ;    /* 01:01 minor version */
        u_int8  PTYPE = bind_ack;   /* 02:01 bind ack PDU */
        u_int8  pfc_flags;          /* 03:01 flags */
        byte    packed_drep[4];     /* 04:04 NDR data rep format label*/
        u_int16 frag_length;        /* 08:02 total length of fragment */
        u_int16 auth_length;        /* 10:02 length of auth_value */
        u_int32  call_id;           /* 12:04 call identifier */

      /* end common fields */

        u_int16 max_xmit_frag;      /* 16:02 max transmit frag size */
        u_int16 max_recv_frag;      /* 18:02 max receive  frag size */
        u_int32 assoc_group_id;     /* 20:04 returned assoc_group_id */
        port_any_t sec_addr;        /* 24:yy optional secondary address 
                                     * for process incarnation; local port
                                     * part of address only */
      /* restore 4-octet alignment */

        u_int8 [size_is(align(4))] pad2;

      /* presentation context result list, including hints */

        p_result_list_t     p_result_list;    /* variable size */

      /* optional authentication verifier */
      /* following fields present iff auth_length != 0 */

        auth_verifier_co_t   auth_verifier; /* xx:yy */
    } rpcconn_bind_ack_hdr_t;`

**Comment by jefffhaynes** [comment]
Gotcha. Ok, should be an easy fix.

**Comment by jefffhaynes** [comment]
Pushed as 5.8.2.  Let me know if you run into any issues with it.

**Comment by grandkarabas** [comment]
Works fine! Thank you Jeff :)

**Comment by jefffhaynes** [comment]
Great, glad to hear it!

---------------
I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses - Johannes Kepler




On Mon, Dec 19, 2016 at 4:51 AM -0500, "grandkarabas" <notifications@github.com> wrote:












Closed #51.
