### ISSUE TITLE
Should I use value converter or a custom serialization?

### ISSUE THREAD

**Issue by FYGonzalo** [jefffhaynes/BinarySerializer#52]
Hello, first of all I am sorry if this isn't the correct place to ask, I am not so familiar with github.

This framework is amazing, I'm glad that I found it, but I am a bit confused about Value Converter.
I have a packet structure where one of its props is the payload length (as UInt16), it comes "ciphered" (xor with 0x1357) and I am not sure if this is the proper use for a Value Converter.

This is most because I don't get why I can't set a ConverterType for FieldOrder, maybe because the length result from the convert may be different of the field size? 
I know I can set a the converter as a proper of FieldSize but then I am defining the size two times because I already have set the variable as UInt16. 

Anyway, really sorry if this is not the correct place or my question offends you (I don't know if my question is stupid), I readed the readme many times but I don't get it.

Thank!

**EDIT:** nvm, I misunderstood all, value converter is for bindings (https://github.com/jefffhaynes/BinarySerializer/issues/19). Seems like the proper way to do this is having some method that "cipher" all the header before serializing the packet, and decipher after deserializing it.
Looks like I did not read well all readme (excuse me, english is not my native language).

**EDIT2:** I think this will be a good moment to use a custom serialization, What do you think? The code will be cleaner and will abstract all the packet processing (encryption, compression and checksum), is there something I am missing or its so good as it sounds?

**Comment by jefffhaynes** [comment]
Hm, that seems reasonable and if I'm understanding I would use a sort of xor converter as the converter on a FieldLength attribute. Sorry, not in front of a computer or I would write code. 
I'm not following the part about FieldOrder. Maybe you can explain that more or show an example. 

---------------
I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses - Johannes Kepler




On Mon, Dec 19, 2016 at 12:26 PM -0500, "Gonzalo Fernandez Yaique" <notifications@github.com> wrote:












Reopened #52.

**Comment by FYGonzalo** [comment]
Yeah, I was a little confused about how works FieldLength and now I figured that when the field is serialized, the frameworks set the length to the field that FieldLength is pointer.

I am having another problem now with an enum, I don't really know whats going on.
When I try serialize my objects I get an exception:
> An unhandled exception of type 'System.InvalidOperationException' occurred in BinarySerializer.dll
> Additional information: There was an error reflecting member 'OperationCode'


```c#

    public enum AOOperationCodes : UInt16
    {
        CipherKey = ((UInt16)(0x0000)),
        LoginData = ((UInt16)(0x0000)),
    }

    class AOMessage
    {
        [Ignore]
        private AOOperationCodes operationCode;

        [Ignore]
        private AOObject aoObject; 

        [FieldOrder(0)]
        public AOOperationCodes OperationCode
        {  get { return operationCode;  } set { operationCode = value; } }

        [FieldOrder(1)]
        public AOObject AoObject
        { get { return aoObject; } set { aoObject = value; }  }

        public AOMessage(AOObject aoObject)
        {
            this.aoObject = aoObject;
            operationCode = this.aoObject.GetOperationCode();
        }
        public AOMessage() { }
    }
```

Also had a problem with a custom serialization that uses a Queue, the constructor creates a new queue and then I fill that queue from another class and all goes ok, but when I try serialize it, the queue is empty, solved this using a List but I wish know if there is something I am missing, already checked my code and I never call the constructor again or something like that but the constructor is called twice.

If you want to take a deep look into my code (Just in case you want to see something else) , here is where I define all the clases to be serialized:
https://github.com/FYGonzalo/DevilsHateLS/blob/master/DevilsHateLS/AOProtocol.cs

And here is where I serialize all those objects
https://github.com/FYGonzalo/DevilsHateLS/blob/master/DevilsHateLS/AOOutgoingMessageManager.cs

Just a short explanation of what I am doing so if you read my code may be easier to understand:
I am emulating a game server. Each TCP packet has a 6 bytes header, the first ushort has the payload length, the next ushort has the number of messages (AKA objects or classes) contained in the payload, the next ushort indicates if the payload is encrypted or compressed and the last is byte is checksum.
I created a custom serializator for a class I called "AOPacketPayload" because the payload can be encrypted or compressed, so there I can write all the code to decompress or decipher it (I didn't wrote that yet).
After that, the payload becomes an array of messages, because an unencrypted payload should look like this:
[FirstMessageLength][FirstMessage],[SecondMessageLength][SecondMessage],...
Each message comes with an operation code that identifiques the class that it belongs, and the rest of bytes are the props of each class.
[OperationCode][ObjectData]

**Comment by jefffhaynes** [comment]
Ok I'll try to look at it as soon as possible

---------------
I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses - Johannes Kepler




On Mon, Dec 19, 2016 at 7:58 PM -0500, "Gonzalo Fernandez Yaique" <notifications@github.com> wrote:












Yeah, I was a little confused about how works FieldLength and now I figured that when the field is serialized, the frameworks set the length to the field that FieldLength is pointer.


I am having another problem now with an enum, I don't really know whats going on.

When I try serialize my objects I get an exception:



An unhandled exception of type 'System.InvalidOperationException' occurred in BinarySerializer.dll

Additional information: There was an error reflecting member 'OperationCode'

    public enum AOOperationCodes : UInt16
    {
        CipherKey = ((UInt16)(0x0000)),
        LoginData = ((UInt16)(0x0000)),
    }

    class AOMessage
    {
        [Ignore]
        private AOOperationCodes operationCode;

        [Ignore]
        private AOObject aoObject; 

        [FieldOrder(0)]
        public AOOperationCodes OperationCode
        {  get { return operationCode;  } set { operationCode = value; } }

        [FieldOrder(1)]
        public AOObject AoObject
        { get { return aoObject; } set { aoObject = value; }  }

        public AOMessage(AOObject aoObject)
        {
            this.aoObject = aoObject;
            operationCode = this.aoObject.GetOperationCode();
        }
        public AOMessage() { }
    }


Also had a problem with a custom serialization that uses a Queue, the constructor creates a new queue and then I fill that queue from another class and all goes ok, but when I try serialize it, the queue is empty, solved this using a List but I wish know if there is something I am missing, already checked my code and I never call the constructor again or something like that but the constructor is called twice.


If you want to take a deep look into my code (Just in case you want to see something else) , here is where I define all the clases to be serialized:

https://github.com/FYGonzalo/DevilsHateLS/blob/master/DevilsHateLS/AOProtocol.cs


And here is where I serialize all those objects

https://github.com/FYGonzalo/DevilsHateLS/blob/master/DevilsHateLS/AOOutgoingMessageManager.cs


Just a short explanation of what I am doing so if you read my code may be easier to understand:

I am emulating a game server. Each TCP packet has a 6 bytes header, the first ushort has the payload length, the next ushort has the number of messages (AKA objects or classes) contained in the payload, the next ushort indicates if the payload is encrypted or compressed and the last is byte is checksum.

I created a custom serializator for a class I called "AOPacketPayload" because the payload can be encrypted or compressed, so there I can write all the code to decompress or decipher it (I didn't wrote that yet).

After that, the payload becomes an array of messages, because an unencrypted payload should look like this:

[FirstMessageLength][FirstMessage],[SecondMessageLength][SecondMessage],...

Each message comes with an operation code that identifiques the class that it belongs, and the rest of bytes are the props of each class.

[OperationCode][ObjectData]

**Comment by FYGonzalo** [comment]
Man, I am really sorry for the spam, I didn't knew how to see the exception throwed by the BinarySerializer when I did Serialize().

The problem with the enum happens when two items have the same value, I googled that and people says it shouldn't throw error but it does in my code, maybe is something inside the framework.

The problem with the queue may be because I tried to do something by the quick way, I thought that defining the props Length and Count in my custom serialized class would let me FieldCount and FieldLength with that class, obviously it throws an exception that the class isnt a collection and therbefore cant use those decorators. Such a dumbass! I will take a look to solve this and then will tell you if the constructor is still called twice.

**Comment by jefffhaynes** [comment]
Ok, so a couple of things:

-- The framework doesn't know the semantics of a Queue or how to handle it so I would simply serialize or deserialize a List<AOMessageArrayItem>.  You don't need custom serialization since each item is self-describing (has a length).  The framework will simply serialize all the items in the list or deserialize until the stream runs out.  If this is a network stream where a timeout is possible then you'll have to have a terminator of some sort.

-- The issue with the enums is that if the op codes have the same value the framework doesn't know how to deserialize them.  If it encounters 0x0, is that CipherKey or LoginData?  If it can't resolve this it throws an exception.

Let me know if that makes sense.  I can try to fix some of it for you when I have more time, possibly in a few days.

**Comment by FYGonzalo** [comment]
Seems like my brain was confused, after sleep I think I got it. I can't even explain what I was thinking about, was something like that many bindings did the process before serialization and then others after, and a really mess, don't try to understand what was going on in my head.

Well, if I didn't missunderstod again, it seems pretty easy now.
This is the workflow I need to follow when serializing:
> --> Serialize the list of AOMessageArrayItem (AKA payload) 
> --> if ceByte's values (the compression & encryption indicator) is 1 or 2, then I gotta compress nor encrypt the payload 
> --> Calculate the checksum of payload and put that into the checksum byte 
> --> Set the number of messages contained on the payload & cipher xoring with the length of payload (I'm gonna get this number when I call a new instance of AOPacket passing a list or a single packet)
> --> Cipher the ceByte xoring with the length of payload
> --> Cipher the length of payload xoring with 0x1357

When deserializing its something similar:
> --> Read payload length & xor with 0x1357 (AKA real payload length) 
> --> Read the number of messages contained on the payload & decrypt it xoring with real payload length (I can skip this, don't need when deserializing)
> --> Read the ceByte and decrypt it xoring with real payload length 
> --> Read the checksum byte
> --> Calculate the payload checksum to check the integrity of the packet comparing it with the checksum result contained in the incoming packet header
> --> if ceByte's value is 1 or 2, then decompress nor decrypt the payload
> --> Finally, deserialize payload into a list of AOMessageArrayItem

So I rewrote my code because I don't need AOMessageArrayItem anymore, instead I just have AOMessages and AOObjects.
I didn't implemented yet all those custom FieldValues attributes so don't know if I this aproach works, going to do that right now and update this comment with the result.

This is my AOProtocol class now.
```C#
    class NewAOPacket
    {
        // True when we need to serialize a calculated checksum
        // False when we need to calculate the checksum but still deserialize the 
        // ones that comes in the packet header.
        [Ignore]
        public bool sending = false;

        [FieldOrder(0)]
        public ushort PayloadLength { get; set; }

        [FieldOrder(1)]
        [HeaderNOMCipher("PayloadLength", ConverterType = typeof(PacketPayloadLengthConverter))] // An extension of FieldValue to do xor with the payloadLength and return ushort
        public ushort NumberOfMessages { get; set; }

        [FieldOrder(2)]
        [HeaderCEBCipher("PayloadLength", ConverterType = typeof(PacketPayloadLengthConverter))] // Same as above but returning byte
        public byte CEByte { get; set; }
     
        // Stores the packet header checksum value when deserializing
        [FieldOrder(3)]
        [SerializeWhen("sending", false)]
        public byte ReadedChecksum { get; set; }
        
        // Calculates the payload checksum value when serializing or deserializing but only used when serializing.
        [FieldOrder(3)]
        [SerializeWhen("sending", true)]
        [PayloadChecksum("AoMessageArrayItems")] // An extension of FieldValue with the checksum code
        public byte Checksum { get; set; }     

        [FieldOrder(4)]
        [FieldLength("PayloadLength", ConverterType = typeof(PacketPayloadLengthConverter))]
        [PayloadCipher("CEByte")] // An extension of FieldValue with the ciphing code
        public List<AOMessage> AOMessagesList { get; set; }

        public NewAOPacket() { }

        public NewAOPacket(AOObject aoObject, byte CEByte)
        {
            sending = true;

            AOMessagesList = new List<AOMessage>();
            AOMessage aoMessage = new AOMessage(aoObject);
            AOMessagesList.Add(aoMessage);
            NumberOfMessages = 1;
            this.CEByte = CEByte;     
        }

        public NewAOPacket(List<AOObject> aoObjects, byte CEByte)
        {
            sending = true;

            // Load all aoClasses into List of AOObjects and blablabla...
        } 

        // Let us check if is the packet is valid before use messages that it contains.
        // We will only use this method when receiving a packet
        public bool isValid()
        {
            return (Checksum == ReadedChecksum);
        }
    }

    public enum AOOperationCodes : ushort
    {
          EncryptionKey = 16,
          LoginData = 0,
    }

    // Structure in which object is sent
    class AOMessage
    {
        [FieldOrder(0)]
        public ushort MessageLength { get; set; }

        [FieldOrder(1)]
        public AOOperationCodes OperationCode { get; set; }

        [FieldOrder(2)]
        [FieldLength("MessageLength")]
        [Subtype("OperationCode", AOOperationCodes.EncryptionKey, typeof(AOEncryptionKey))]
        [SubtypeDefault(typeof(AODefaultObject))]
        public AOObject Object{ get; set; }   

        public AOMessage(AOObject aoObject)
        {
            this.Object= aoObject;
        }
    }

    // The "master" class
    abstract class AOObject{ }

    // Just in case there is a message that hasn't a specific class 
    class AODefaultObject : AOObject
    {
        [FieldOrder(0)]
        public byte[] Buffer { get; set; }
    }

    // This is one of the objects I will send using the packet class
    class AOEncryptionKey : AOObject
    {
        [Ignore]
        private const Int32 ENCRYPTIONKEY_LENGTH = 16;

        [FieldOrder(0)]
        public ushort Unknowed { get; set; }

        [FieldOrder(1)]
        public byte[] EncryptionKey { get; set; }

        public AOEncryptionKey()
        {
            Random keyGenerator = new Random();
            this.EncryptionKey = new Byte[ENCRYPTIONKEY_LENGTH];
            keyGenerator.NextBytes(this.EncryptionKey);
        }
    }
```


The enums problem makes sense, I didn't thought that, anyway seems like the protocol haven't repeated operation codes, the value I used for AOCipherKey (now called AOEncryptionKey) was wrong.

**Comment by FYGonzalo** [comment]
NVM, my problem is that I wanted to use a lot of fieldvalues and binding with nonsense because I thought it would be more elegant and not because of functionalities.

This works for me, I only need to make another method to restore all messages from the packet when I am receiving a message (a method where I deserialize the payload byte array)

```C#
class AOPacket
    {
        [FieldOrder(0)]
        public ushort PayloadLength { get; set; }

        [FieldOrder(1)]
        public ushort NumberOfMessages { get; set; }

        [FieldOrder(2)]
        public byte CEByte { get; set; }

        [FieldOrder(3)]
        public byte Checksum { get; set; }

        [FieldOrder(4)]
        [FieldLength("PayloadLength", ConverterType = typeof(PacketPayloadLengthConverter))]
        public byte[] Payload { get; set; }

        public AOPacket(AOObject aoObject)
        {
            BinarySerializer binarySerializer = new BinarySerializer();
            AOMessage aoMessage = new AOMessage(aoObject);
            AOMessageArrayItem aoMessageArrayItem = new AOMessageArrayItem(aoMessage);

            MemoryStream memoryStream = new MemoryStream();
            binarySerializer.Serialize(memoryStream, aoMessageArrayItem);
            Payload = memoryStream.ToArray();

            /// If CEByte's value is 1 or 2, should encrypt nor compress here

            
            NumberOfMessages = (ushort)(1 ^ Payload.Length);
            CEByte = (byte)(0 ^ Payload.Length);
            Checksum = AOChecksum.GetChecksum(Payload, 0);
        }

   
    }

    public enum AOOperationCodes : ushort
    {
        EncryptionKey = 16,
        LoginData = 0,
    }

    class AOMessageArrayItem
    {
        [FieldOrder(0)]
        public ushort MessageLength { get; set; }

        [FieldOrder(1)]
        [FieldLength("MessageLength")]
        public AOMessage AoMessage { get; set; }

        public AOMessageArrayItem(AOMessage aoMessage)
        {
            this.AoMessage = aoMessage;
        }

        public AOMessageArrayItem()
        { }
    }

    // Structure in which object is sent
    class AOMessage
    {
        [FieldOrder(1)]
        public AOOperationCodes OperationCode { get; set; }

        [FieldOrder(2)]
        [Subtype("OperationCode", AOOperationCodes.EncryptionKey, typeof(AOEncryptionKey))]
        [SubtypeDefault(typeof(AODefaultObject))]
        public AOObject Object { get; set; }

        public AOMessage(AOObject aoObject)
        {
            this.Object = aoObject;
        }
    }

    // The "master" class
    abstract class AOObject { }

    // Just in case there is a message that hasn't a specific class 
    class AODefaultObject : AOObject
    {
        [FieldOrder(0)]
        public byte[] Buffer { get; set; }
    }

    // This is one of the objects I will send using the packet class
    class AOEncryptionKey : AOObject
    {
        [Ignore]
        private const Int32 ENCRYPTIONKEY_LENGTH = 16;

        [FieldOrder(0)]
        public ushort Unknowed { get; set; }

        [FieldOrder(1)]
        public byte[] EncryptionKey { get; set; }

        public AOEncryptionKey()
        {
            Random keyGenerator = new Random();
            this.EncryptionKey = new Byte[ENCRYPTIONKEY_LENGTH];
            keyGenerator.NextBytes(this.EncryptionKey);
        }
    }
```

Sorry for wasting your time but also thanks!

**Comment by jefffhaynes** [comment]
No worries. I'll still try to take a look in the next few days. I think there are one or two things you might be able to simplify further. 

---------------
I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses - Johannes Kepler




On Tue, Dec 20, 2016 at 1:39 PM -0500, "Gonzalo Fernandez Yaique" <notifications@github.com> wrote:












NVM, my problem is that I wanted to use a lot of fieldvalues and binding with nonsense because I thought it would be more elegant and not because of functionalities.


This works for me, I only need to make another method to restore all messages from the packet when I am receiving a message (a method where I deserialize the payload byte array)
class AOPacket
    {
        [FieldOrder(0)]
        public ushort PayloadLength { get; set; }

        [FieldOrder(1)]
        public ushort NumberOfMessages { get; set; }

        [FieldOrder(2)]
        public byte CEByte { get; set; }

        [FieldOrder(3)]
        public byte Checksum { get; set; }

        [FieldOrder(4)]
        [FieldLength("PayloadLength", ConverterType = typeof(PacketPayloadLengthConverter))]
        public byte[] Payload { get; set; }

        public AOPacket(AOObject aoObject)
        {
            BinarySerializer binarySerializer = new BinarySerializer();
            AOMessage aoMessage = new AOMessage(aoObject);
            AOMessageArrayItem aoMessageArrayItem = new AOMessageArrayItem(aoMessage);

            MemoryStream memoryStream = new MemoryStream();
            binarySerializer.Serialize(memoryStream, aoMessageArrayItem);
            Payload = memoryStream.ToArray();

            /// If CEByte's value is 1 or 2, should encrypt nor compress here

            
            NumberOfMessages = (ushort)(1 ^ Payload.Length);
            CEByte = (byte)(0 ^ Payload.Length);
            Checksum = AOChecksum.GetChecksum(Payload, 0);
        }

   
    }

    public enum AOOperationCodes : ushort
    {
        EncryptionKey = 16,
        LoginData = 0,
    }

    class AOMessageArrayItem
    {
        [FieldOrder(0)]
        public ushort MessageLength { get; set; }

        [FieldOrder(1)]
        [FieldLength("MessageLength")]
        public AOMessage AoMessage { get; set; }

        public AOMessageArrayItem(AOMessage aoMessage)
        {
            this.AoMessage = aoMessage;
        }

        public AOMessageArrayItem()
        { }
    }

    // Structure in which object is sent
    class AOMessage
    {
        [FieldOrder(1)]
        public AOOperationCodes OperationCode { get; set; }

        [FieldOrder(2)]
        [Subtype("OperationCode", AOOperationCodes.EncryptionKey, typeof(AOEncryptionKey))]
        [SubtypeDefault(typeof(AODefaultObject))]
        public AOObject Object { get; set; }

        public AOMessage(AOObject aoObject)
        {
            this.Object = aoObject;
        }
    }

    // The "master" class
    abstract class AOObject { }

    // Just in case there is a message that hasn't a specific class 
    class AODefaultObject : AOObject
    {
        [FieldOrder(0)]
        public byte[] Buffer { get; set; }
    }

    // This is one of the objects I will send using the packet class
    class AOEncryptionKey : AOObject
    {
        [Ignore]
        private const Int32 ENCRYPTIONKEY_LENGTH = 16;

        [FieldOrder(0)]
        public ushort Unknowed { get; set; }

        [FieldOrder(1)]
        public byte[] EncryptionKey { get; set; }

        public AOEncryptionKey()
        {
            Random keyGenerator = new Random();
            this.EncryptionKey = new Byte[ENCRYPTIONKEY_LENGTH];
            keyGenerator.NextBytes(this.EncryptionKey);
        }
    }


Sorry for wasting your time but also thanks!

**Comment by jefffhaynes** [comment]
I haven't tried this but I added a FieldChecksum attribute to 6.0 that you could potentially use instead of calculating the checksum yourself.

**Comment by FYGonzalo** [comment]
Thank you, sorry for the late response but I wasn't at home.
