### ISSUE TITLE
Error during deserialization from a NetworkStream, with SubType and IBinarySerializable

### ISSUE THREAD

**Issue by lamesjinden** [jefffhaynes/BinarySerializer#55]
I'm attempting to deserialize from a NetworkStream. In my case, I'm using the SubType attribute to target a type that contains an IBinarySerializable type.

Take a look [here](https://github.com/lamesjinden/BinarySerializerRepro)

Does this look right? Maybe there is a better way of going about this.

Thanks,
-james

System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Error deserializing 'type 'BinarySerializerRepro.ChunkContainer''.  See inner exception for detail.
  Source=BinarySerializer
  StackTrace:
   at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(BoundedStream stream, EventShuttle eventShuttle)
   at BinarySerialization.BinarySerializer.Deserialize(Stream stream, Type type, Object context)
   at BinarySerialization.BinarySerializer.Deserialize[T](Stream stream, Object context)
   at BinarySerializerRepro.Program.Main(String[] args) in E:\src\BinarySerializerRepro\Program.cs:line 149

Inner Exception 1:
InvalidOperationException: Error deserializing 'type 'BinarySerializerRepro.ChunkContainer''.  See inner exception for detail.

Inner Exception 2:
InvalidOperationException: Error deserializing 'member 'Chunk''.  See inner exception for detail.

Inner Exception 3:
InvalidOperationException: Error deserializing 'member 'Customs''.  See inner exception for detail.

Inner Exception 4:
InvalidOperationException: Not supported on non-seekable streams

**Comment by jefffhaynes** [comment]
Lames Jinden, you rascal. I'll take a look this weekend. 

---------------
I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses - Johannes Kepler




On Wed, Feb 22, 2017 at 11:49 PM -0500, "james" <notifications@github.com> wrote:












I'm attempting to deserialize from a NetworkStream. In my case, I'm using the SubType attribute to target a type that contains an IBinarySerializable type.


Take a look here


Does this look right? Maybe there is a better way of going about this.


Thanks,

-james


System.InvalidOperationException occurred

HResult=0x80131509

Message=Error deserializing 'type 'BinarySerializerRepro.ChunkContainer''.  See inner exception for detail.

Source=BinarySerializer

StackTrace:

at BinarySerialization.Graph.ValueGraph.ValueNode.Deserialize(BoundedStream stream, EventShuttle eventShuttle)

at BinarySerialization.BinarySerializer.Deserialize(Stream stream, Type type, Object context)

at BinarySerialization.BinarySerializer.Deserialize[T](Stream stream, Object context)

at BinarySerializerRepro.Program.Main(String[] args) in E:\src\BinarySerializerRepro\Program.cs:line 149


Inner Exception 1:

InvalidOperationException: Error deserializing 'type 'BinarySerializerRepro.ChunkContainer''.  See inner exception for detail.


Inner Exception 2:

InvalidOperationException: Error deserializing 'member 'Chunk''.  See inner exception for detail.


Inner Exception 3:

InvalidOperationException: Error deserializing 'member 'Customs''.  See inner exception for detail.


Inner Exception 4:

InvalidOperationException: Not supported on non-seekable streams

**Comment by jefffhaynes** [comment]
Fixed in 7.0.1

**Comment by lamesjinden** [comment]
great. thanks.

**Comment by jefffhaynes** [comment]
I only fixed the exception. I haven't looked at the rest of it but let me know if it's not working or you want me to look at something. 

---------------
I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses - Johannes Kepler




On Sat, Feb 25, 2017 at 4:29 PM -0500, "james" <notifications@github.com> wrote:












great. thanks.

**Comment by lamesjinden** [comment]
Per the discussion in issue #57, I verified that I'm limited to NetFx 4.5. Any chance you can apply this fix to your 6.0.* release?

Thanks,
-james

**Comment by jefffhaynes** [comment]
Yeah. Just give me a day or so. 

---------------
I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses - Johannes Kepler




On Mon, Feb 27, 2017 at 4:33 PM -0500, "james" <notifications@github.com> wrote:












Per the discussion in issue #57, I verified that I'm limited to NetFx 4.5. Any chance you can apply this fix to your 6.0.* release?


Thanks,

-james

**Comment by jefffhaynes** [comment]
Fixed in 6.0.3
