### ISSUE TITLE
Serialization of null fields

### ISSUE THREAD

**Issue by FYGonzalo** [jefffhaynes/BinarySerializer#65]
The documentation says
> Null values are allowed; however, bear in mind that this can lead to unstable definitions. While serialization may work, deserialization may fail if the framework is unable to deduce which fields are meant to be null and which are not.

If you serialize a object with unassigned string field (which has FieldLength decorator), the output byte array will be filled with zeros.

IE: 
```csharp
    public class TestClass
    {
        [FieldOrder(0)]
        [FieldLength(5)]
        public string Text { get; set; }
    }
```

The output will be:
> { 0x00, 0x00, 0x00, 0x00, 0x00 }

_This also works with int, short, long, or any other value field (obviously those without FieldLength/FieldCount because are fixed size)_

But the result isn't the same when FieldLength/FieldCount is applied to an array of values types or complex objects.
If you serialize this class:
```csharp
    public class TestClass
    {
        [FieldOrder(0)]
        [FieldCount(5)]
        public short[] ShortArray { get; set; }
    }
```

The result is a byte array with zero bytes (Length = 0).

The same problem happens when you try to serialize a class which contains a complex field.
IE:
```csharp
    public class ComplexClass
    {
        [FieldOrder(0)]
        [FieldLength(5)]
        public string Text { get; set; }
    }

    public class TestClass
    {
        [FieldOrder(0)]
        public ComplexClass ComplexClass { get; set; }
    }
```

If you serialize ComplexClass alone (without assign any value to Text), the result is a byte array with five "0x00" bytes, but when you serialize TestClass (without assign any value to ComplexClass field) the result is a byte array with no bytes.

If you serialize a object and then deserialize it, if it has some of those cases, the result won't be the same.

I think because of the existence of SerializeWhen and SerializeWhenNot, when a field is null and isn't decorated with any of those two attributes, the framework must fill the size of those classes with 0x00 bytes (just calling the constructor of the class).

**Comment by jefffhaynes** [comment]
The first issue with the Count wasn't supported but I did just add support.  I need to test it a bit more and then I'll push a new package.

The second issue I think is the expected behavior.  While I believe one can make an argument for padding a null field that is declared to have a certain length or count, I don't see that the same argument can be made if the parent is null.  I believe in your example you are not instantiating the ComplexClass and therefore the framework never attempts to serialize the Text field.
