### ISSUE TITLE
Packet object and packet data (byte[]) must be inheritable at the same time

### ISSUE THREAD

**Issue by serkanayaz** [jefffhaynes/BinarySerializer#73]
Packet object and packet data (byte[]) must be inheritable at the same time. For example:

public class Frame
    {
        [FieldOrder(0)]
        public PacketType PacketType { get; set; }

[FieldOrder(1)]
        public uint PacketLength { get; set; }

[FieldOrder(2)]
        [Subtype("PacketType", PacketType.Message, typeof(MessagePacket))]
        [Subtype("PacketType", PacketType.Control, typeof(ControlPacket))]
        [SubtypeDefault(typeof(UnknownPacket))]
        **public BasePacket PacketObject { get; set; }**

[Ignore]
        **[FieldOrder(???)]**
        [FieldLength("PacketLength")]
        [FieldChecksum("Checksum", Mode = ChecksumMode.Xor)]
        [SubtypeDefault(typeof(byte[]))] **//PacketObject datas for all packet type (PacketData equals PacketObject)**
        **public byte[] PacketData { get; set; }**

[FieldOrder(3)]
        public byte Checksum { get; set; }
    }

**Comment by jefffhaynes** [comment]
I'm sorry, I don't understand. If you want the default subtype to be a byte array then simply encapsulate the byte array in a derived class that is part of the inheritance hierarchy. But I don't totally understand what you're trying to say.

________________________________

**Comment by serkanayaz** [comment]
I'm sorry, I'm english little. PacketObject (type is object) and PacketData (type is byte array), but PacketObject field is equal to PacketData field, different only types. I want to get PacketObject field as both object (BasePacket) and byte array. Thank you for your interest.

**Comment by jefffhaynes** [comment]
I don't think what you're trying to do is supported but can you post the code for PacketObject?

**Comment by serkanayaz** [comment]
I can will do when i have time. Thank you.
