### ISSUE TITLE
Data length of the package to be created

### ISSUE THREAD

**Issue by serkanayaz** [jefffhaynes/BinarySerializer#74]
How can I get the package data size needed for deserialize the data?

**Comment by jefffhaynes** [comment]
Sorry, I don't understand.  Can you give me an example of what you're trying to do?

**Comment by serkanayaz** [comment]
**Now it's working like:** 5 bytes data -> [Converter(BinarySerializer)] -> PacketObject
or
PacketObject -> [Converter(BinarySerializer)] -> 5 bytes data

**I want to function for required data length. For example:**
PacketObject packetObject = new PacketObject();
BinarySerializer.GetRequiredDataLength(packetObject); **//return type int and return value 5**
or
BinarySerializer.GetRequiredDataLength<PacketObject>(); **//return type int and return value 5**

**Comment by jefffhaynes** [comment]
BinarySerializer defines SizeOf, but all it does is Serialize into a sort of "/dev/null" stream and return the total length.  Is that what you're looking to do?

**Comment by serkanayaz** [comment]
"SizeOf" is good resolve for object. But no it's not for class type. I need data length of class type for now, i don't need data length of class object. For example:

int packetDataLength = BinarySerializer.GetRequiredDataLength<PacketObject>(); // I need this. PacketObject is class type, it's not object.

**Comment by jefffhaynes** [comment]
Ok I’ll look at it

**Comment by jefffhaynes** [comment]
I realized why I never added this.  The values of the type fields can also effect the size of the serialized graph.  If I had a type-based method it would only be useful for default field values or graphs with no variable sized fields, which seems of limited use.  Can you give me a specific example of something you're trying to do with this?  Thanks

**Comment by serkanayaz** [comment]
First of all thank you for your reply. I understand that my needs don't be. I can close issue if you want?

I can say for my example: I have a buffer in my code. And I want to read from this buffer for protocol data. Sample protocol format: [2 bytes Data Length] [N bytes Data] [1 byte EOF]. Firstly I read 2 bytes from buffer, secondly I read N bytes from buffer, thirdly I read 1 byte from buffer. I need data length when i will read from buffer for every read.

I be very happy if you have a different idea for this problem?

**Comment by serkanayaz** [comment]
First of all thank you for your reply. I understand that my needs don't be. I can close issue if you want?

I can say for my example: I have a buffer in my code. And I want to read from this buffer for protocol data. Sample protocol format: [2 bytes Data Length] [N bytes Data] [1 byte EOF]. I need 2+N+1 bytes for fill of BinarySerializer model. Total data length is unknown of BinarySerializer model because the data block is variable.

Can we solve the problem when changing the algorithm or scenario as follows?: Firstly I read 2 bytes from buffer for [DataLengthBlock], secondly I read N bytes from buffer for [DataBlock], thirdly I read 1 byte from buffer for [EofBlock]. I need data length when I will read from buffer for every read. We need the psuedo code below for like this for this scenario:

Buffer buffer = ...;
BinarySerializer binarySerializer = new BinarySerializer();
ModelFiller<PacketObject> modelFiller = new ModelFiller<PacketObject>(binarySerializer);
int fieldDataLength = modelFiller.GetFirstFieldDataLength();
while (fieldDataLength != -1)
{
	byte[] fieldData = buffer.ReadData(fieldDataLength);
	fieldDataLength = modelFiller.FillField(fieldData); //Return value is data length for next field. It's take -1 value if model is ready (or filled all field)
}
PacketObject packetObject = modelFiller.GetObject();

I be very happy if you have a different idea for this problem?

**Comment by jefffhaynes** [comment]
That's essentially what the serializer is doing already.  If you pass a stream into the Deserialize method, it will read the 2 bytes and then determine from that how much to read into the data block.

```c#
public class Block
{
    [FieldOrder(0)]
    public ushort Length { get; set; }

    [FieldOrder(1)]
    [FieldLength("Length")]
    public byte[] Data { get; set; }

    [FieldOrder(2)]
    public byte End { get; set; }
}

var block = serializer.Deserialize<Block>(stream);

```

If you need to you can contain this in a list of blocks or call the method repeatedly.  Is this what you're looking for?

**Comment by serkanayaz** [comment]
No because I don't have all binary data of PacketObject. I have only know data count for next loop on current iteration.

Example my buffer data ([Array Index]: Value): [0]: 0, [1]: 4, [2]: 1, [3]: 2, [4]: 3, [5]: 4, [6]: 255, ...........

**Initialize:** I set readable data count (2 bytes(ushort) for "Length" field).
**First Loop:** I read 2 bytes from buffer ([0]: 0, [1]: 4). Now, I know value of Length field (4 bytes). And I know data count for read in next loop ( fieldDataLength = modelFiller.FillField(fieldData); ).
**Second Loop:** I read 4 bytes from buffer ([2]: 1, [3]: 2, [4]: 3, [5]: 4). Now, I know value of Data field. And I know data count for read in next loop ( fieldDataLength = modelFiller.FillField(fieldData); ) (1 byte for EOF).
**Third Loop:** I read 1 byte from buffer ([6]: 255). Now, I know value of EOF field. And I know PacketObject successful because I take -1 from FillField function ( fieldDataLength = modelFiller.FillField(fieldData); ). After I exit from while loop and I create PacketObject object ( PacketObject packetObject = modelFiller.GetObject(); )

How can we solve this scenario?

**Comment by jefffhaynes** [comment]
Yes, that is how the serializer works. It will read two bytes from the stream then use that to read four bytes and so on. Have you tried the code I sent?

—
Planning for failure is even dumber than regular planning
________________________________
