### ISSUE TITLE
CRC Checks

### ISSUE THREAD

**Issue by rikimaru0345** [jefffhaynes/BinarySerializer#79]
Hi,
I was wondering what the usecase is for having CRC attributes available when they are not checked after the object got deserialized.

Maybe to communicate with some device that needs a crc?

Is there a public API in BinarySerializer that a user can use to calculate the CRC themselves and then compare it? 

Why not have a simple bool option in the CRC attribute to enable checking after deserialization?

I'm probably missing something here...

**Comment by jefffhaynes** [comment]
They're generated during serialization.  I suppose they could be checked during deserialization but I never really came up with a strategy for error handling that I liked.  I take it you have a use case that would benefit from checking them during deserialization?  I feel like most people use the library for interop with older systems and usually want to generate CRCs but don't seem to care as much about checking them.

**Comment by rikimaru0345** [comment]
>I feel like most people use the library for interop with older systems and usually want to generate CRCs but don't seem to care as much about checking them.

I see. My use case would be error checking saved files as well as network packets.

As for automated checking, you could just throw an exception, but personally I don't have a need for that. It doesn't have to be automated, but a public API to compute the checksum of an object (skipping the CRC field(s) obviously haha) would be really nice! :)

**Comment by jefffhaynes** [comment]
Actually it just occurred to me that specifying the binding mode would allow you to effectively ignore CRC exceptions during deserialization.  Let me work on it.

**Comment by VDBorovikov** [comment]
We develop a low power devices with a small set of resources. These devices communicate with server using our binary protocol requires a checksum. So to be able to CRC checking during deserialization is a good idea.

**Comment by jefffhaynes** [comment]
I’m still working on this. It’s just going to take a bit of work.

**Comment by jefffhaynes** [comment]
Pushed in 7.9
