### ISSUE TITLE
SerializeWhen . Feature suggestion. Would be a nice feature to allow a calculated value or array.

### ISSUE THREAD

**Issue by mikedavison** [jefffhaynes/BinarySerializer#82]
I have fields which are serialized only on certain "versions". However I have multiple version cases where the field can be serializes. The desired actions can be performed by specifying multiple "SerializeWhen" attributes. But this makes for a lot of coding if there are many fields.
Would be good if there was a way to either calculate the SerializeWhen for the specific field or pass multiple values.

e.g 
[SerializeWhen("Version", 30,31,35)]  // serialize if version matches any of the values.

or
[SerializeWhen("Version", >30)] // serialize if version greater than 30

**Comment by jefffhaynes** [comment]
This can be accomplished as follows.

```c#
public class SerializeWhenClass
{
    [FieldOrder(0)]
    public int Version { get; set; }

    [FieldOrder(1)]
    [SerializeWhen("Version", true, ConverterType = typeof(VersionBoolConverter), ConverterParameter = 30)]
    public bool Value { get; set; }
}
```
```c#
class VersionBoolConverter : IValueConverter
{
    public object Convert(object value, object parameter, BinarySerializationContext context)
    {
        var version = (int) value;
        var minVersion = (int) parameter;

        return version > minVersion;
    }

    public object ConvertBack(object value, object parameter, BinarySerializationContext context)
    {
        throw new NotSupportedException();
    }
}
```

**Comment by mikedavison** [comment]
If you are interested  here is a real easy to implementation that allows this feature without the need for  a  value converter. Attached is a revised conditional binding code.
Changes: when the conditional value is an array it will compare against each element and return true of any match.
example usage:
`[SerializeWhen(nameof(FileContext.version), new int[] { 124, 128, 132 }, RelativeSourceMode = RelativeSourceMode.SerializationContext)]`

Notice the value is an array. so if the `version `matches any of these it returns true. Saves having to have multiple `SerializeWhen` entries and avoids a `valueconverter`. 

[ConditionalBinding.zip](https://github.com/jefffhaynes/BinarySerializer/files/4209472/ConditionalBinding.zip)
