### ISSUE TITLE
Why does [Ignore] on a getter only property need one way binding set.

### ISSUE THREAD

**Issue by mikedavison** [jefffhaynes/BinarySerializer#83]
I have the following code
[Ignore ]  public int Version  {  get {  return 30; }   }
and ...
[SerializeWhen("Version", 30)] [FieldOrder(1)] public short headerLength;

Running Deserialize gives the following message relating to the property "Version".

"This attribute does not support forward binding.  Consider specifying a BindingMode of OneWayToSource."

This is obviously because there is no setter. Why does one way binding need to be set for an ignored field? Consider changing functionality so that it automatically sets one way binding for [Ignore] fields that only have a getter.

**Comment by jefffhaynes** [comment]
Ok, interesting. Let me work on it.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by mikedavison** [comment]
Ok so to get around this error I need to add OneWayToSource. If my code is...
[Ignore ] public int Version { get { return 30; } }
what is the syntax to add the binding mode?

**Comment by jefffhaynes** [comment]
You would add it on the SerializeWhen attribute.  Sorry, not in front of a computer at the moment but it should be BindingMode = OneWayToSource

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by mikedavison** [comment]
Thanks that works. Hmmm.. see my other post about a suggested change to specifying multiple versions for SerializeWhen.  I have multiple objects with up to 74 fields needing multiple "versions" . If I have to also ass the binding mode to each SerializeWhen statement, the attribute code is going to be huge... :).

**Comment by jefffhaynes** [comment]
You could specify a converter I think. Like a “greater than” converter that takes a threshold as a converter parameter. Then serializewhen true.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by jefffhaynes** [comment]
Also, make sure you aren’t over-specifying the format. For example, if subsequent versions of the spec added fields but the container is length bound then you can simply make them nullable and the serializer will ignore them. However, if subsequent versions made breaking changes that you can’t elegantly recover from then yeah, you need conditional serialization. However I would always regard it as a last resort.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by jefffhaynes** [comment]
If you want, send me the spec for whatever you’re doing and I can take a look.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by jefffhaynes** [comment]
I pushed 7.8.1, which fixes it so you don't have to specify the binding mode
