### ISSUE TITLE
Compile Error BinarySerializer. No overload for method `CopyTo` takes 3 arguments.

### ISSUE THREAD

**Issue by mikedavison** [jefffhaynes/BinarySerializer#84]
Just downloaded project  after you fixed issue #83. Gets compile error:
StreamValueNode.cs

line 66 : `stream.CopyTo(nullStream, (int)length.Value, CopyToBufferSize);`

Error:
No overload for method `CopyTo` takes 3 arguments.

**Comment by jefffhaynes** [comment]
That's an extension method in StreamExtensions.cs.  Can you verify that class is present?

**Comment by mikedavison** [comment]
I recopied from zip and it worked that time. Not sure what went wrong before. Thanks you can close.

**Comment by jefffhaynes** [comment]
Great
