### ISSUE TITLE
Non standard boolean

### ISSUE THREAD

**Issue by mikedavison** [jefffhaynes/BinarySerializer#85]
Hi there. I have file structure with non standard boolean values. Some are UInt16 and some are UInt32
In both cases true = 1, false = 0. 
Is there an attribute that can be used to serialize as either Uint16 or Uint32 AND convert boolean correctly.

Tks.

**Comment by mikedavison** [comment]
Stet. Just realised the answer. Just use properties to wrapper boolean. :)

**Comment by mikedavison** [comment]
close

**Comment by jefffhaynes** [comment]
That would work but you should also be able to specify SerializeAs.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by mikedavison** [comment]
How would you use SerializeAs? SerializeAs would specify whether its a short or int but how can SerializeAs change the saved values of true and false? In the c# world I thought true = -1 and false = 0. I need true to be 1.

**Comment by jefffhaynes** [comment]
[SerializeAs(SerializedType.UInt2)]
public bool Value { get; set; }

1 is true, 0 is false

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by mikedavison** [comment]
Thanks.
