### ISSUE TITLE
How do I specify for an object to Deserialize itself.

### ISSUE THREAD

**Issue by mikedavison** [jefffhaynes/BinarySerializer#87]
I have a class with the following method:
```
public class DoDeserialize{
        public Header h;
        public void Read(string fileName)
        {
            // read file
            fs = new FileStream(fileName, FileMode.Open);
            fs.Position = 0;
            BinarySerializer serializer = new BinarySerializer();
            serializer.Deserialize(fs, this.GetType(), this); // this option does not populate h
            
        }
}
```
How do I call the deserialize on itself?  You mention something in your calls to an optional 'context'  parameter. I can't find reference to what you mean by 'context' in your documentation.  In addition you have plenty of examples in documentation on how to use "Serialize" but little on how to use "Deserialize". Suggest a few relevant examples to be added to documentation and include examples of how to use the optional context parameter.

Thanks.

**Comment by jefffhaynes** [comment]
Deserialize returns the deserialized object. In your example you could simply deserialize the header since it’s the only thing in the class. If there are more fields then I suggest creating a container object. I’ll look at adding more examples.

The serialization context won’t help you here. It’s used for more complex cases where you need to bind to external objects or for use in custom serialization.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by mikedavison** [comment]
Thanks for the reply. The code is a cut down version there is a lot more than just the header. 
Sounds like the "context" is possibly what I need. I need to pass an external  value to all of the headers and other structures. Can you provide an example of how "context" is used.
In my particular case  see comment in code. **** . I need to somehow pass a "Version" value to each of the structures to aid deserialization.

Note: this is a very complex binary structured file I am trying to read.  The code example below is only to show the concept of what I am trying to do.
```
public class DoDeserialize{
        [FieldOrder(1)] public Headerstructure h;  // needs Version
        [FieldOrder(2)] public Structure2 o2; // needs Version
        [FieldOrder(3)] public Structure3 o3; // needs Version
         .. many more structures

        [Ignore] public int Version { get; set; }

        public void Read(string fileName)
        {
            // read file
            fs = new FileStream(fileName, FileMode.Open);
            fs.Position = 0;
            BinarySerializer serializer = new BinarySerializer();
            serializer.Deserialize(fs, this.GetType(), ???); 
            // **** How do I pass the Version value to each of the structures
        }
}
```

**Comment by mikedavison** [comment]
Closing. Resubmitting as different question.

**Comment by jefffhaynes** [comment]
Check out the signal strength field on this class.

https://github.com/jefffhaynes/XBee/blob/master/XBee.Core/Frames/AtCommands/NetworkDiscoveryResponseData.cs

—
Planning for failure is even dumber than regular planning
________________________________
