### ISSUE TITLE
Overriding and ignoring properties

### ISSUE THREAD

**Issue by VDBorovikov** [jefffhaynes/BinarySerializer#89]
Hi Jeff.
I have some models with complex inheritance. One of the case looks like:
```csharp
    public class AbstractOrder
    {
        [SerializeAs(SerializedType.UInt2)]
        public virtual string RequestId { get; set; }
    }

    public class Order : AbstractOrder
    {
        [FieldOrder(0)]
        public int I { get; set; }

        [FieldOrder(1)]
        public int RId { get; set; }

        [Ignore]
        public override string RequestId => RId.ToString("X8");
    }
```
It looks like `[Ignore]` attribute on overriden property is ignored :) So, we get an excpetion during serialization.
```csharp
var bs = new BinarySerializer();

var order = new Order(){I = 5, RId = 10};

var ms = new MemoryStream();
bs.Serialize(ms, order);
ms.Position = 0;
var o = bs.Deserialize<Order>(ms);
Console.ReadLine();
```

Is it possible to do such things?

**Comment by jefffhaynes** [comment]
The ignore is only used during the serialization phase, but the property will still be reflected in case you try to late-bind to it (for example, in unknown types that are not discoverable in the type graph but are introduced later during serialization). However, I agree it shouldn’t stop you from doing that. Let me play around with it and see if there’s a way to have both.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by jefffhaynes** [comment]
Interesting, it looks like this is actually a side-effect of the framework not correctly handling overridden properties.  Let me work on a fix.

**Comment by jefffhaynes** [comment]
This is going to be tricky.  I recommend avoiding inheritance in properties until I can come up with a solution.  It's just not something I considered in the design and I'm not even sure what the correct behavior would be in all circumstances.

**Comment by jefffhaynes** [comment]
Actually I figured it out.  Pushed in 7.9.1.
