### ISSUE TITLE
BinarySerializer deserialization performance

### ISSUE THREAD

**Issue by abrasat** [jefffhaynes/BinarySerializer#9]
I did some measurements regarding the performance of the BinarySerializer serialization/deserialization, and I got quite huge times for the deserialization.
A binary message with some about 10000 bytes needs each time about 1200 msec for deserialization (the BinarySerializer object is created only once and reused, no debugger events were defined during this measurement).

What is weird is that the serialization process that generates the 10000 bytes back from the c# class takes only 10 msec or even less.

Only the deserialization of each length-prefixed string takes 15 msec (to get these times I had to reactivate the debug events)

2015-03-23T10:56:32.7437607+01:00 [DEBUG] BinarySerialization.BinarySerializer -
 Deserializing B_ID, stream offset 0
2015-03-23T10:56:32.7447608+01:00 [DEBUG] BinarySerialization.BinarySerializer -
 Deserialized B_ID, (300101000), stream offset 4
2015-03-23T10:56:32.7477611+01:00 [DEBUG] BinarySerialization.BinarySerializer -
 Deserializing B_Name, stream offset 4
2015-03-23T10:56:32.7497613+01:00 [DEBUG] BinarySerialization.BinarySerializer -
 Deserializing Length, stream offset 4
2015-03-23T10:56:32.7527616+01:00 [DEBUG] BinarySerialization.BinarySerializer -
 Deserialized Length, (2), stream offset 6
2015-03-23T10:56:32.7577621+01:00 [DEBUG] BinarySerialization.BinarySerializer -
 Deserializing Value, stream offset 6
2015-03-23T10:56:32.7607624+01:00 [DEBUG] BinarySerialization.BinarySerializer -
 Deserialized Value, (W1), stream offset 10
2015-03-23T10:56:32.7627626+01:00 [DEBUG] BinarySerialization.BinarySerializer -
 Deserialized B_Name, (W1), stream offset 55

The c# class looks like this: 

public class Entry
{

    [FieldOrder(0)]
    public byte Length { get; set; }

    [FieldOrder(1)]
    [FieldLength("Length")]
    public string Value { get; set; }
}

public class ElementClass 
{

    [FieldOrder(0)]
    public Int32 B_ID { get; set; } 

    [FieldOrder(1)]
    [FieldLength(51)]
    public Entry B_Name { get; set; } 
...

}

Earlier I had this code to get the length-prefixed string by reading "manually" the length from the first byte:

...

        private string _B_Name;
        [FieldOrder(1)]
        [FieldLength(51)]
        [SerializeAs(Encoding = "UTF-8")]
        public string B_Name //{ get; set; } 
        {
             get
             {
                 return this._B_Name;
             }
             set
             {
                 this._B_Name = LengthPrefixedStringToString(value);
             }
        }

...

where:

        internal static string LengthPrefixedStringToString(string value)
        {
            string tempStr = String.Empty;
            if (value != null)
            {
                try
                {
                    value.Trim();
                    int strLen = value.Length;
                    if (strLen > 0)
                    {
                        if (strLen > 255) {
                            throw new Exception("Maximum length allowed for pascal strings is 255");
                        }
                        char lenCh = value[0];
                        byte len = Convert.ToByte(lenCh);
                        if (strLen > (int)len)
                        {
                            tempStr = value.Substring(1, len);
                        }
                    }
                }
                catch { }
            }
            return tempStr;
        }

With this code, the deserialization of the 10000 bytes from the binary message takes only 30 msec or even less (still not perfect, if I compare to the serialization time in the other direction, but much much better than the 1200 msec above).

Is there any way to significantly improve the performance of the deserializer, especially regarding such length-prefixed strings, constructed as above ?

**Comment by jefffhaynes** [comment]
Deserialization is more expensive than serialization because the objects have to be instantiated but I'll take a look and try to see what's causing it.

**Comment by jefffhaynes** [comment]
I guess I don't quite see where the 10000 bytes come from.  How many Entry fields or other fields are in your ElementClass?

**Comment by jefffhaynes** [comment]
Never mind, I found some crazy optimizations in reporting the serialization context.  Try 3.9 and hopefully you'll see about a 66% speed improvement.

**Comment by abrasat** [comment]
Indeed, really crazy :-), big improvement in the deserialization performance. With my 10000 bytes of binary data (yes, there are lots of Entry fields, other fields and also lists of other fields there), the first deserialization took some 30 msec, the next ones less than 10 msec.

**Comment by jefffhaynes** [comment]
Awesome, thank you for the feedback!

**Comment by abrasat** [comment]
Do you eventually have some benchmarks regarding the BinarySerializer performance comparison (size, speed) with other serializers ?

**Comment by jefffhaynes** [comment]
Which serializers did you have in mind?

**Comment by abrasat** [comment]
Protobuf, JSON, ...
http://www.maxondev.com/serialization-performance-comparison-c-net-formats-frameworks-xmldatacontractserializer-xmlserializer-binaryformatter-json-newtonsoft-servicestack-text/

**Comment by jefffhaynes** [comment]
While I agree there may be some opportunity to do performance comparisons (and I probably will spend time on it), this is largely comparing apples to oranges.  The point of BinarySerializer is not to do one thing incredibly fast (a la JSON NS), but to do arbitrary serializations at reasonable speed.  If you really need incredibly fast serialization for a very specific thing, you're always going to be better off writing your own specialized engine.

**Comment by jefffhaynes** [comment]
I haven't done in-depth analysis but based on some rough looking, it now seems to be on par with BinaryFormatter.  It's going to be tricky to make it much faster since the PCL restriction means no IL gen available.
