### ISSUE TITLE
How to present protocol at bit level？

### ISSUE THREAD

**Issue by demon-iak** [jefffhaynes/BinarySerializer#92]
I have a lot of protocols
 that have many bit fields, I see that binary serilazer operates at byte level, can I use binary serilazer at bit level?

**Comment by jefffhaynes** [comment]
Not really. You can define flags of course and interpret bytes at the bit level but the serializer does not understand bits. I am working on adding some amount of support for this but it will take some time.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by demon-iak** [comment]
@jefffhaynes Thank you for you hard work! I have been using BinarySerilazer for some of my projects and it is very good to use. I'll try to study the code and figure out what I can do for this.

**Comment by jefffhaynes** [comment]
Thanks, I’m glad you like it!  I’ve made some progress on this problem but it is extremely complicated. I’m afraid I still have a lot of work to do.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by jefffhaynes** [comment]
This is now supported in 8.0.
