### ISSUE TITLE
Error when opening binary serilizer in VS2015 

### ISSUE THREAD

**Issue by gcharles81** [jefffhaynes/BinarySerializer#97]
Hello I am having an error if I try to open the Binary Serilizer solution in VS2015 - 

The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format.

Thanks Charles

**Comment by danm-de** [comment]
Hi @gcharles81,
I was able to open the solution using the free version of VS2017 without any problems. My build environment did not show any errors.
Were you able to fix this issue? If yes - could you please provide assistence about how to fix it? Maybe a pull-request?

Thanks and regards,
Daniel
(I am not the author of BinarySerializer)
